import type { WeekPlan } from "../types";

// Challenge #3 — Ethiopia & Eritrea: Beyaynetu.
// The full seven-week arc, every week built out into an executable WeekPlan
// (engine + 7 days + costed shopping list). cuisine is "ethiopian"; the engine
// is cuisine-agnostic, so these slot into the shared content arrays, tagged by
// cuisine. These are the curated, pregenerated defaults — the AI menu generator
// lets users compose variations on top of the same recipe pool.
//
// Dinner slugs reference recipes in src/content/recipes/*. Engine lines reference
// base-recipe slugs where apt (teff-injera, berbere, niter-kibbeh,
// pot-of-red-lentils).

export const ethWeek1Injera: WeekPlan = {
  slug: "eth-week-1-injera",
  number: 1,
  cuisine: "ethiopian",
  theme: "The Fasting Plate",
  title: "Week 1 — The Fasting Plate",
  description:
    "The everyday vegan rhythm of the Orthodox fast — lentil and pea wots over injera, the balanced plate eaten most days of the year. Start here: it's how the Horn actually eats, and it clears the protein floor with no meat at all.",
  context:
    `For up to two hundred days a year the Orthodox fast forbids all animal products, so the everyday plate was built entirely from teff, lentils, peas, and greens — and made good enough to want on a holy day. This is that plate: a round of injera laid with a few wots, eaten with the hands, no fork and no meat. Injera is the constant beneath all of it — you ferment and griddle a batch ahead and eat on it all week — so the week isn't about the bread but the rhythm of the fasting table: a fiery wot and a gentle one, a green, a scoop of shiro. The humble daily meal that is also, when the fast breaks, the feast.`,
  dishes: [
    "Shiro wot — the fifteen-minute everyman wot",
    "Misir wot — the fiery red-lentil staple",
    "Kik alicha — gentle, turmeric split peas",
    "A small beyaynetu — a little of each on one injera round",
  ],
  proteinNote:
    "Teff itself carries a surprising amount of protein; the legume wots that sit on the injera do the rest. The floor is met with shiro and lentils, no meat.",
  bonus: false,
  preciousThread: "A bag of true ivory teff flour for the injera.",
  engine: [
    "teff-injera — start the teff ferment Sunday so injera is ready midweek; keep a spoon of ersho to seed the next batch",
    "berbere — toast and grind a jar to power every wot on the arc",
    "niter-kibbeh — render a jar of spiced clarified butter",
    "pot-of-red-lentils — a base pot to turn into misir wot and alicha all week",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "shiro-wot over the first injera",
      estCalories: 700,
      estProtein: 26,
    },
    {
      day: "Mon",
      dinner: "misir-wot over injera",
      estCalories: 710,
      estProtein: 27,
    },
    {
      day: "Tue",
      dinner: "dinich-wot (potato) over injera with a spoon of shiro",
      estCalories: 680,
      estProtein: 22,
    },
    {
      day: "Wed",
      dinner: "shiro-wot, the thicker tegabino style, in a clay pot",
      estCalories: 720,
      estProtein: 28,
    },
    {
      day: "Thu",
      dinner: "misir-alicha and gomen over injera",
      estCalories: 690,
      estProtein: 24,
    },
    {
      day: "Fri",
      dinner: "yemisir-kik (lentils + split peas) over injera",
      estCalories: 730,
      estProtein: 30,
    },
    {
      day: "Sat",
      dinner: "a small beyaynetu — shiro, misir, kik, gomen on one injera round",
      estCalories: 740,
      estProtein: 29,
    },
  ],
  shopping: [
    { item: "Ivory teff flour", qty: "~3–4 lb", cost: 9.0, note: "the precious thread — the grain the whole cuisine rests on" },
    { item: "Split red lentils (misir)", qty: "2 lb", cost: 3.2 },
    { item: "Shiro powder (chickpea/bean flour, spiced)", qty: "1 lb", cost: 4.0 },
    { item: "Yellow split peas (kik)", qty: "1 lb", cost: 1.5 },
    { item: "Dried fava beans (for ful)", qty: "1 lb", cost: 1.6 },
    { item: "Dried red chiles + spices (for berbere)", qty: "a batch", cost: 5.0, spansWeeks: true, note: "makes the jar that powers the arc" },
    { item: "Butter (for niter kibbeh)", qty: "1 lb", cost: 4.0, spansWeeks: true },
    { item: "Red onions", qty: "~4 lb", cost: 4.0 },
    { item: "Garlic + ginger", qty: "2 heads / 1 hand", cost: 2.5, spansWeeks: true },
    { item: "Collard greens / kale", qty: "1 bunch", cost: 1.5 },
    { item: "Potatoes", qty: "~2 lb", cost: 1.5 },
    { item: "Tomatoes", qty: "~2 lb", cost: 2.5 },
    { item: "Green chiles (jalapeño/serrano)", qty: "a handful", cost: 1.0 },
    { item: "Flaxseed (telba)", qty: "small bag", cost: 1.5, spansWeeks: true },
    { item: "Wheat/barley flour (for dabo kolo)", qty: "2 lb", cost: 1.5 },
    { item: "Lemons", qty: "4", cost: 1.5 },
    { item: "Oil", qty: "", cost: 4.0, spansWeeks: true },
  ],
  firstShopTotal: 30,
  steadyStateWeekly: 18,
};

export const ethWeek2Misir: WeekPlan = {
  slug: "eth-week-2-misir",
  number: 2,
  cuisine: "ethiopian",
  theme: "Misir",
  title: "Week 2 — Misir (red-lentil wot)",
  description:
    "The fiery brick-red heart of the table. Red lentils melt into a silky stew over a long onion sweat and bloomed berbere — the dish people picture when they picture this cuisine — with its gentle turmeric twin as the cool counterweight.",
  context:
    `The fiery brick-red heart of the table. Misir wot — red lentils melted into a silky stew over a long, patient onion sweat and a generous berbere bloom — is the dish people picture when they picture this cuisine, and its gentle twin misir alicha (turmeric, no chile) is the cool counterweight. A pot of split red lentils costs almost nothing and gives about 18g of protein per cooked cup. The whole dish lives on two moves done right: a long low onion melt and blooming the berbere in hot niter kibbeh before any liquid goes in. Leftover misir torn into day-old injera becomes misir fitfit.`,
  dishes: [
    "Misir wot (fiery red-lentil stew)",
    "Misir alicha (gentle, turmeric-bright)",
    "Misir fitfit (leftovers + day-old injera)",
    "Ful for breakfast",
  ],
  proteinNote: "Red lentils ~18g protein per cooked cup; a plate of misir clears most of the day's floor with no meat.",
  bonus: false,
  preciousThread: "A jar of fresh-toasted berbere — the one pantry investment that powers the whole arc.",
  engine: [
    "pot-of-red-lentils — a big base pot, split between fiery wot and gentle alicha",
    "berbere — keep the jar stocked; bloomed fresh into every pot",
    "niter-kibbeh — the fat the berbere blooms in",
    "teff-injera — a stack of injera, with offcuts saved for fitfit",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "misir-wot over injera — the headline pot",
      estCalories: 710,
      estProtein: 28,
    },
    {
      day: "Mon",
      dinner: "misir-wot with a side of dinich-wot",
      estCalories: 720,
      estProtein: 27,
    },
    {
      day: "Tue",
      dinner: "misir-alicha and atakilt-wot over injera",
      estCalories: 680,
      estProtein: 22,
    },
    {
      day: "Wed",
      dinner: "misir-wot, the pot deepened on day three",
      estCalories: 700,
      estProtein: 26,
    },
    {
      day: "Thu",
      dinner: "yemisir-kik (lentils + split peas) over injera",
      estCalories: 730,
      estProtein: 30,
    },
    {
      day: "Fri",
      dinner: "shiro-wot for a change of pace, with injera",
      estCalories: 690,
      estProtein: 25,
    },
    {
      day: "Sat",
      dinner: "misir-wot and misir-alicha side by side — fire and gentle on one injera",
      estCalories: 740,
      estProtein: 29,
    },
  ],
  shopping: [
    { item: "Split red lentils (misir)", qty: "3 lb", cost: 4.8, note: "the bank — the whole week runs on this" },
    { item: "Berbere spices (top up the jar)", qty: "a batch", cost: 4.0, spansWeeks: true },
    { item: "Yellow split peas (for yemisir-kik)", qty: "1 lb", cost: 1.5 },
    { item: "Shiro powder", qty: "1/2 lb", cost: 2.0 },
    { item: "Green lentils (for azifa)", qty: "1 lb", cost: 1.6 },
    { item: "Dried fava beans (for ful)", qty: "1 lb", cost: 1.6 },
    { item: "Teff flour", qty: "~3 lb", cost: 7.0 },
    { item: "Red onions", qty: "~5 lb", cost: 5.0, note: "the long onion sweat eats onions" },
    { item: "Garlic + ginger", qty: "2 heads / 1 hand", cost: 2.5, spansWeeks: true },
    { item: "Collard greens", qty: "1 bunch", cost: 1.5 },
    { item: "Cabbage + carrots + potatoes", qty: "for atakilt/dinich", cost: 3.5 },
    { item: "Tomatoes", qty: "~2 lb", cost: 2.5 },
    { item: "Green chiles", qty: "a handful", cost: 1.0 },
    { item: "Lemons + mustard (for azifa)", qty: "4 / 1 jar", cost: 2.0, spansWeeks: true },
    { item: "Niter kibbeh / butter (top up)", qty: "1/2 lb", cost: 2.0, spansWeeks: true },
    { item: "Oil", qty: "", cost: 4.0, spansWeeks: true },
  ],
  firstShopTotal: 28,
  steadyStateWeekly: 17,
};

export const ethWeek3Shiro: WeekPlan = {
  slug: "eth-week-3-shiro",
  number: 3,
  cuisine: "ethiopian",
  theme: "Shiro",
  title: "Week 3 — Shiro",
  description:
    "The weeknight workhorse. Ground roasted chickpea flour whisked into a spiced onion base becomes a velvety, garlicky wot in fifteen minutes — so humble it was historically the only wot many families ate outside festivals, yet the dish everyone misses from home.",
  context:
    `The weeknight workhorse. Shiro is ground roasted chickpea (or broad-bean) flour whisked into a spiced onion base — a velvety, garlicky wot ready in fifteen minutes from a bag of flour. So humble it was historically the only wot many families ate outside festivals, yet so good it's the dish everyone misses from home. The thicker clay-pot version is tegabino; with a little meat it becomes bozena shiro; stiffened overnight and torn into injera it becomes shiro fitfit. The clump-killer is to slurry the flour into water first and whisk hard before it ever hits the hot pot.`,
  dishes: [
    "Shiro wot (and the thicker tegabino)",
    "Bozena shiro (with a little meat)",
    "Shiro fitfit (the zero-waste morning after)",
    "Kategna alongside",
  ],
  proteinNote: "Chickpea flour, cheap and fast — shiro is the quickest protein on the arc, pantry flour plus an onion.",
  bonus: false,
  preciousThread: "A nub of niter kibbeh to finish the shiro.",
  engine: [
    "niter-kibbeh — render or top up the jar; shiro wants it",
    "berbere — bloomed into the shiro base",
    "teff-injera — a stack, offcuts saved for fitfit and kategna",
    "pot-of-red-lentils — a small base pot for variety alongside the shiro",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "shiro-wot, the headline, over fresh injera",
      estCalories: 690,
      estProtein: 24,
    },
    {
      day: "Mon",
      dinner: "shiro-wot, tegabino style, in a clay pot",
      estCalories: 710,
      estProtein: 26,
    },
    {
      day: "Tue",
      dinner: "bozena shiro — shiro studded with a little seared meat",
      estCalories: 760,
      estProtein: 33,
    },
    {
      day: "Wed",
      dinner: "shiro-wot with a side of dinich-wot",
      estCalories: 700,
      estProtein: 23,
    },
    {
      day: "Thu",
      dinner: "misir-wot for contrast, with injera",
      estCalories: 720,
      estProtein: 28,
    },
    {
      day: "Fri",
      dinner: "shiro-wot over injera, with gomen",
      estCalories: 690,
      estProtein: 25,
    },
    {
      day: "Sat",
      dinner: "bozena shiro again — the feast-day shiro to close the week",
      estCalories: 770,
      estProtein: 34,
    },
  ],
  shopping: [
    { item: "Shiro powder (chickpea/bean flour)", qty: "2 lb", cost: 8.0, note: "the bank for the week" },
    { item: "Beef or lamb (for bozena shiro)", qty: "~3/4 lb", cost: 5.0, note: "a little meat seasons the whole pot" },
    { item: "Niter kibbeh / butter", qty: "1 lb", cost: 4.0, spansWeeks: true, note: "the precious thread this week" },
    { item: "Split red lentils", qty: "1 lb", cost: 1.6 },
    { item: "Yellow split peas (for kik alicha)", qty: "1/2 lb", cost: 0.8 },
    { item: "Green lentils (for azifa)", qty: "1/2 lb", cost: 0.8 },
    { item: "Dried fava beans (for ful)", qty: "1 lb", cost: 1.6 },
    { item: "Teff flour", qty: "~3 lb", cost: 7.0 },
    { item: "Red onions", qty: "~4 lb", cost: 4.0 },
    { item: "Garlic + ginger", qty: "2 heads / 1 hand", cost: 2.5, spansWeeks: true },
    { item: "Collard greens", qty: "1 bunch", cost: 1.5 },
    { item: "Potatoes", qty: "~2 lb", cost: 1.5 },
    { item: "Tomatoes", qty: "~2 lb", cost: 2.5 },
    { item: "Green chiles + lemons", qty: "a handful / 4", cost: 2.0 },
    { item: "Berbere spices (top up)", qty: "", cost: 2.0, spansWeeks: true },
    { item: "Oil", qty: "", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 30,
  steadyStateWeekly: 18,
};

export const ethWeek4Kik: WeekPlan = {
  slug: "eth-week-4-kik",
  number: 4,
  cuisine: "ethiopian",
  theme: "Kik & Alicha",
  title: "Week 4 — Kik & Alicha (gentle peas)",
  description:
    "The week the heat rests. Yellow split peas become sunny, turmeric-bright dishes — whole and creamy, or whipped to a smooth purée — the soothing, mild counterweight that makes the fiery wots taste even better by contrast.",
  context:
    `The week the heat rests. Yellow split peas become sunny, turmeric-bright dishes: kik alicha (whole and creamy), ater kik alicha (a smooth purée), and their spicy cousin kik wot when you want fire. The alicha dishes are the soothing, mild counterweight that makes the fiery wots taste even better by contrast — the platter needs both the cool and the heat. Split peas bring about 16g protein per cooked cup. A pinch of korarima (Ethiopian cardamom) or besobela (sacred basil) at the end lifts a gentle pea pot from plain to perfumed.`,
  dishes: [
    "Kik alicha (whole, creamy split peas)",
    "Ater kik alicha (smooth purée)",
    "Kik wot (the spicy cousin)",
    "Yemisir kik (peas + lentils pooled)",
  ],
  proteinNote: "Split peas ~16g protein per cooked cup; pooled with lentils in yemisir kik, the day clears the floor easily.",
  bonus: false,
  preciousThread: "Korarima (Ethiopian cardamom) and besobela (sacred basil) for fragrance.",
  engine: [
    "A big pot of yellow split peas, split between gentle alicha and fiery kik wot",
    "niter-kibbeh — the fat for blooming the kik wot's berbere",
    "berbere — for the spicy half of the split-pea pot",
    "teff-injera — a stack, offcuts saved for fitfit",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "kik-alicha and gomen over injera",
      estCalories: 680,
      estProtein: 22,
    },
    {
      day: "Mon",
      dinner: "kik-wot (the spicy split-pea pot) over injera",
      estCalories: 700,
      estProtein: 25,
    },
    {
      day: "Tue",
      dinner: "yemisir-kik — peas and lentils pooled, over injera",
      estCalories: 730,
      estProtein: 31,
    },
    {
      day: "Wed",
      dinner: "kik-wot with a side of dinich-wot",
      estCalories: 690,
      estProtein: 23,
    },
    {
      day: "Thu",
      dinner: "misir-wot for contrast, with injera",
      estCalories: 720,
      estProtein: 28,
    },
    {
      day: "Fri",
      dinner: "shiro-wot, with injera and a green",
      estCalories: 700,
      estProtein: 25,
    },
    {
      day: "Sat",
      dinner: "kik-wot and kik-alicha side by side — the same pea, fire and gentle",
      estCalories: 720,
      estProtein: 27,
    },
  ],
  shopping: [
    { item: "Yellow split peas (kik)", qty: "3 lb", cost: 4.5, note: "the bank for the week — gentle and fiery from one bag" },
    { item: "Split red lentils (for yemisir-kik + misir)", qty: "1.5 lb", cost: 2.4 },
    { item: "Green lentils (for azifa)", qty: "1 lb", cost: 1.6 },
    { item: "Shiro powder", qty: "1/2 lb", cost: 2.0 },
    { item: "Dried fava beans (for ful)", qty: "1 lb", cost: 1.6 },
    { item: "Korarima / cardamom + besobela (basil)", qty: "small", cost: 3.0, spansWeeks: true, note: "the precious thread — fragrance for the alicha" },
    { item: "Teff flour", qty: "~3 lb", cost: 7.0 },
    { item: "Red onions", qty: "~4 lb", cost: 4.0 },
    { item: "Garlic + ginger", qty: "2 heads / 1 hand", cost: 2.5, spansWeeks: true },
    { item: "Collard greens", qty: "1 bunch", cost: 1.5 },
    { item: "Cabbage + carrots + potatoes", qty: "for atakilt/dinich", cost: 3.5 },
    { item: "Green chiles + lemons", qty: "a handful / 4", cost: 2.0 },
    { item: "Berbere spices (top up)", qty: "", cost: 2.0, spansWeeks: true },
    { item: "Niter kibbeh / butter (top up)", qty: "1/2 lb", cost: 2.0, spansWeeks: true },
    { item: "Flaxseed (for telba)", qty: "small", cost: 1.0, spansWeeks: true },
    { item: "Oil", qty: "", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 26,
  steadyStateWeekly: 16,
};

export const ethWeek5Gomen: WeekPlan = {
  slug: "eth-week-5-gomen",
  number: 5,
  cuisine: "ethiopian",
  theme: "Gomen & Greens",
  title: "Week 5 — Gomen & Greens",
  description:
    "The restorative green week. Collards stewed soft with garlic and ginger, cabbage-carrot-potato in a turmeric base, green beans, and bright cold salads round out the legume-heavy plate with color and freshness — eating the whole garden alongside the bean pot.",
  context:
    `The restorative green week. Gomen (collard greens stewed soft with garlic and ginger), atakilt wot (cabbage, carrot, and potato in a turmeric base), fasolia (green beans and carrots), and bright cold dishes like azifa (a sharp green-lentil salad) round out the legume-heavy plate with color and freshness. This is eating the whole garden alongside the bean pot — a wedge of fresh ayib cheese cools the greens into gomen be ayib on a feast day. And a raw tomato salad tossed with yesterday's injera makes timatim fitfit, so nothing goes to waste.`,
  dishes: [
    "Gomen (collard greens)",
    "Atakilt wot (cabbage, carrot, potato)",
    "Fasolia (green beans + carrots)",
    "Azifa & timatim fitfit (the bright cold dishes)",
  ],
  proteinNote: "Greens add a little; the day still leans on a wot or salad of lentils and a smear of shiro to clear the floor.",
  bonus: false,
  preciousThread: "A wedge of fresh ayib cheese to cool the greens (gomen be ayib).",
  engine: [
    "A big pot of red lentils and a small pot of shiro — the protein the greens can't carry alone",
    "pot-of-red-lentils — the lentil base for misir and azifa",
    "Cleaned and stewed gomen, ready to plate all week",
    "teff-injera — a stack, offcuts for timatim fitfit and kategna",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "gomen and misir-wot over injera",
      estCalories: 700,
      estProtein: 26,
    },
    {
      day: "Mon",
      dinner: "atakilt-wot with a smear of shiro over injera",
      estCalories: 670,
      estProtein: 19,
    },
    {
      day: "Tue",
      dinner: "shiro-wot with gomen on the side",
      estCalories: 700,
      estProtein: 25,
    },
    {
      day: "Wed",
      dinner: "misir-wot and atakilt-wot over injera",
      estCalories: 710,
      estProtein: 27,
    },
    {
      day: "Thu",
      dinner: "kik-alicha and gomen over injera",
      estCalories: 680,
      estProtein: 22,
    },
    {
      day: "Fri",
      dinner: "yemisir-kik over injera, with fasolia",
      estCalories: 730,
      estProtein: 30,
    },
    {
      day: "Sat",
      dinner: "a green-forward beyaynetu — gomen, atakilt, fasolia, misir, shiro on one injera",
      estCalories: 740,
      estProtein: 28,
    },
  ],
  shopping: [
    { item: "Collard greens / kale", qty: "3 bunches", cost: 4.5, note: "the green week" },
    { item: "Green cabbage", qty: "1 head", cost: 2.0 },
    { item: "Green beans (for fasolia)", qty: "1 lb", cost: 2.5 },
    { item: "Carrots", qty: "1 lb", cost: 1.0 },
    { item: "Ayib (or fresh ricotta/farmer cheese)", qty: "~1/2 lb", cost: 4.0, note: "the precious thread — cools the greens" },
    { item: "Split red lentils", qty: "1.5 lb", cost: 2.4 },
    { item: "Green lentils (for azifa)", qty: "1 lb", cost: 1.6 },
    { item: "Shiro powder", qty: "1/2 lb", cost: 2.0 },
    { item: "Yellow split peas (for kik alicha)", qty: "1/2 lb", cost: 0.8 },
    { item: "Dried fava beans (for ful)", qty: "1 lb", cost: 1.6 },
    { item: "Teff flour", qty: "~3 lb", cost: 7.0 },
    { item: "Tomatoes", qty: "~3 lb", cost: 3.5, note: "for timatim fitfit" },
    { item: "Potatoes", qty: "~2 lb", cost: 1.5 },
    { item: "Red onions", qty: "~3 lb", cost: 3.0 },
    { item: "Garlic + ginger + green chiles + lemons", qty: "", cost: 4.0, spansWeeks: true },
    { item: "Berbere + niter kibbeh (top up)", qty: "", cost: 3.0, spansWeeks: true },
    { item: "Oil", qty: "", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 27,
  steadyStateWeekly: 17,
};

export const ethWeek6Eritrean: WeekPlan = {
  slug: "eth-week-6-eritrean",
  number: 6,
  cuisine: "ethiopian",
  theme: "Eritrean Crossover",
  title: "Week 6 — Eritrean Crossover",
  description:
    "The same table, one country east. Eritrean Orthodox families keep the identical fasting calendar and legume repertoire — tsebhi birsen IS misir wot, tsebhi shiro IS shiro, taita IS injera — with a Red-Sea accent of extra fenugreek and a sizzling clay pot.",
  context:
    `The same table, one country east. Eritrean Orthodox families keep the identical fasting calendar and the same legume repertoire — tsebhi birsen is misir wot, tsebhi shiro is shiro, taita is injera — so this week is a lesson in how a single cuisine belongs to two nations. The border is political, not culinary. The accent leans toward the Red Sea: more fenugreek (as in hilbet, a cooling fava-and-fenugreek paste), a deeper onion base, and dishes brought sizzling to the table in a small clay pot. The shared fitfit habit crosses the border too — stale taita revived in spiced oil.`,
  dishes: [
    "Tsebhi birsen (Eritrean red-lentil stew)",
    "Tsebhi shiro (in a sizzling clay pot)",
    "Hilbet (fava + fenugreek paste)",
    "Ful and the shared fasting greens",
  ],
  proteinNote: "Favas and lentils, as ever — the same legume floor, with fenugreek-rich hilbet adding protein and a cooling note.",
  bonus: false,
  preciousThread: "A handful of dried faba beans for hilbet, and fenugreek to soak.",
  engine: [
    "pot-of-red-lentils — the base for tsebhi birsen",
    "A pot of cooked favas, half for ful and half whipped into hilbet",
    "berbere + niter-kibbeh — the same flavor engine, crossing the border",
    "teff-injera (taita) — a stack, offcuts for fitfit",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "tsebhi-birsen over taita — Eritrean misir wot",
      estCalories: 710,
      estProtein: 27,
    },
    {
      day: "Mon",
      dinner: "tsebhi-shiro, sizzling in a clay pot, over taita",
      estCalories: 700,
      estProtein: 25,
    },
    {
      day: "Tue",
      dinner: "tsebhi-birsen with gomen",
      estCalories: 700,
      estProtein: 26,
    },
    {
      day: "Wed",
      dinner: "tsebhi-shiro with a side of atakilt-wot",
      estCalories: 710,
      estProtein: 24,
    },
    {
      day: "Thu",
      dinner: "yemisir-kik over injera, with gomen",
      estCalories: 730,
      estProtein: 30,
    },
    {
      day: "Fri",
      dinner: "tsebhi-birsen and tsebhi-shiro side by side over taita",
      estCalories: 740,
      estProtein: 29,
    },
    {
      day: "Sat",
      dinner: "an Eritrean beyaynetu — tsebhi birsen, shiro, hilbet, gomen on one taita",
      estCalories: 750,
      estProtein: 31,
    },
  ],
  shopping: [
    { item: "Dried faba beans (for ful + hilbet)", qty: "2 lb", cost: 3.2, note: "the precious thread — the Red-Sea bean" },
    { item: "Fenugreek seed (for hilbet)", qty: "small bag", cost: 1.5, spansWeeks: true },
    { item: "Split red lentils (birsen)", qty: "2 lb", cost: 3.2 },
    { item: "Shiro powder", qty: "1 lb", cost: 4.0 },
    { item: "Yellow split peas + green lentils", qty: "1 lb each", cost: 3.1 },
    { item: "Teff flour (taita)", qty: "~3 lb", cost: 7.0 },
    { item: "Red onions", qty: "~5 lb", cost: 5.0, note: "the deep Eritrean onion base" },
    { item: "Garlic + ginger", qty: "2 heads / 1 hand", cost: 2.5, spansWeeks: true },
    { item: "Collard greens", qty: "1 bunch", cost: 1.5 },
    { item: "Cabbage + carrots + green beans", qty: "for atakilt/fasolia", cost: 3.5 },
    { item: "Tomatoes", qty: "~2 lb", cost: 2.5 },
    { item: "Green chiles + lemons", qty: "a handful / 4", cost: 2.0 },
    { item: "Berbere spices (top up)", qty: "", cost: 2.0, spansWeeks: true },
    { item: "Niter kibbeh / butter (top up)", qty: "1/2 lb", cost: 2.0, spansWeeks: true },
    { item: "Oil", qty: "", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 28,
  steadyStateWeekly: 17,
};

export const ethWeek7Beyaynetu: WeekPlan = {
  slug: "eth-week-7-beyaynetu",
  number: 7,
  cuisine: "ethiopian",
  theme: "Beyaynetu",
  title: "Week 7 — Beyaynetu (the feast)",
  description:
    "The whole arc on one platter. A great round of injera laid out with mounds of every dish from the weeks before, and — because the fast is breaking — one indulgence: doro wot or zigni. The fasting platter and the feast platter turn out to be the same platter, with one mound added.",
  context:
    `The whole arc on one platter. Beyaynetu ("a little of each") is the consolidation: a great round of injera laid out with mounds of every dish from the weeks before — misir wot, shiro, kik alicha, gomen, atakilt, a fresh salad — and, because the fast is breaking, one indulgence: doro wot (chicken and eggs in deep berbere) or zigni (spiced beef). One bird or a little beef feeds the whole table, ladled beside the legumes. The fasting platter and the feast platter turn out to be the same platter, with one mound added — proof that fasting and feasting are the same table. And beyaynetu is itself the zero-waste finale: a few spoons of every leftover wot become one abundant feast.`,
  dishes: [
    "Beyaynetu (the full platter)",
    "Doro wot (chicken + eggs in berbere)",
    "Zigni (spiced beef stew)",
    "Kategna and the week's leftovers",
  ],
  proteinNote: "The legumes carry it; the meat is the seasoning luxury. With doro wot or zigni added, the day clears the floor comfortably.",
  bonus: false,
  preciousThread: "One whole chicken for the doro wot (or a little beef for zigni).",
  engine: [
    "The Sunday feast pot: doro-wot — one bird and a dozen eggs braised in deep berbere",
    "A pot of zigni — a little beef stretched across a glossy spiced sauce",
    "The full legume spread: misir wot, shiro, kik alicha (the week's leftovers consolidated)",
    "teff-injera — a double batch for the communal platters",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "doro-wot, fully spiced, with eggs, over injera — the feast",
      estCalories: 780,
      estProtein: 35,
    },
    {
      day: "Mon",
      dinner: "beyaynetu — the full platter, doro wot among the legumes",
      estCalories: 770,
      estProtein: 33,
    },
    {
      day: "Tue",
      dinner: "zigni — spiced beef over injera",
      estCalories: 760,
      estProtein: 34,
    },
    {
      day: "Wed",
      dinner: "beyaynetu — zigni and the legume spread on one round",
      estCalories: 750,
      estProtein: 32,
    },
    {
      day: "Thu",
      dinner: "misir-wot and shiro over injera, resting from the meat",
      estCalories: 710,
      estProtein: 27,
    },
    {
      day: "Fri",
      dinner: "beyaynetu — the legume platter, the everyday feast",
      estCalories: 720,
      estProtein: 28,
    },
    {
      day: "Sat",
      dinner: "the grand beyaynetu finale — every leftover wot, doro, and zigni on one great injera, eaten communally",
      estCalories: 790,
      estProtein: 35,
    },
  ],
  shopping: [
    { item: "Whole chicken (for doro wot)", qty: "~3 1/2 lb bird", cost: 8.0, note: "the precious thread — the feast indulgence" },
    { item: "Beef chuck / stew beef (for zigni)", qty: "~1 lb", cost: 6.0, note: "a little meat, a big platter" },
    { item: "Eggs (for doro wot)", qty: "1 dozen", cost: 4.0 },
    { item: "Split red lentils", qty: "1.5 lb", cost: 2.4 },
    { item: "Shiro powder", qty: "1 lb", cost: 4.0 },
    { item: "Yellow split peas + green lentils", qty: "1 lb each", cost: 3.1 },
    { item: "Dried fava beans (for ful)", qty: "1 lb", cost: 1.6 },
    { item: "Teff flour", qty: "~4 lb", cost: 9.0, note: "double batch for the communal platters" },
    { item: "Red onions", qty: "~6 lb", cost: 6.0, note: "doro and zigni both ride a huge onion sweat" },
    { item: "Garlic + ginger", qty: "3 heads / 1 hand", cost: 3.0, spansWeeks: true },
    { item: "Collard greens + cabbage + carrots", qty: "for the platter greens", cost: 4.0 },
    { item: "Tomatoes", qty: "~2 lb", cost: 2.5 },
    { item: "Green chiles + lemons", qty: "a handful / 6", cost: 2.5 },
    { item: "Berbere spices (top up — the feast wots use a lot)", qty: "", cost: 3.0, spansWeeks: true },
    { item: "Niter kibbeh / butter (top up)", qty: "1 lb", cost: 4.0, spansWeeks: true },
    { item: "Oil", qty: "", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 34,
  steadyStateWeekly: 20,
};

export const ethiopianWeeks: WeekPlan[] = [
  ethWeek1Injera,
  ethWeek2Misir,
  ethWeek3Shiro,
  ethWeek4Kik,
  ethWeek5Gomen,
  ethWeek6Eritrean,
  ethWeek7Beyaynetu,
];
