import type { WeekPlan } from "../types";

// Challenge #4 — Greece: the Orthodox fasting table.
// The full seven-week arc, every week built out into an executable WeekPlan
// (engine + 7 days + costed shopping list). cuisine is "greek"; the engine
// is cuisine-agnostic, so these slot into the shared content arrays, tagged by
// cuisine. These are the curated, pregenerated defaults — the AI menu generator
// lets users compose variations on top of the same recipe pool.
//
// Dinner slugs reference recipes in src/content/recipes/*. The Greek foundation —
// good olive oil, a pot of dried legumes, bread or barley rusk (paximadi),
// lemon, and prepped horta — is the constant base, carried in every week's engine,
// never a week theme. Each theme is a real category of dinner you actually eat.

export const grWeek1Fasolada: WeekPlan = {
  slug: "gr-week-1-fasolada",
  number: 1,
  cuisine: "greek",
  theme: "Fasoláda & Beans",
  title: "Week 1 — Fasoláda",
  description:
    "The dish often called the national food of Greece. Dried white beans simmered slow with olive oil, tomato, celery, and carrot into a soup so plain and so good it fed the country through every lean century — the bean pot that anchors the whole arc.",
  context:
    `The dish often called the national food of Greece. Fasoláda — dried white beans simmered slow with a long pour of olive oil, tomato, celery, and carrot — is the plainest thing imaginable and the food people mean when they say "Greek home cooking." It is nistísimo, fasting food: no meat, no dairy, and so it lands on the table through the long Orthodox fasts that fill nearly half the calendar. A pot of dried beans costs almost nothing and gives roughly 15g of protein per cooked cup; finished with raw oil and lemon and eaten with bread, it is a complete meal. The same pot becomes gigantes plaki when the big beans go in the oven, and the zero-waste hero is dakos — dried barley rusk softened with tomato, oil, and a crumble of cheese, the Cretan answer to never wasting stale bread.`,
  dishes: [
    "Fasoláda (white-bean soup)",
    "Gigantes plaki (baked giant beans)",
    "Mavromátika me spanáki (black-eyed peas + spinach)",
    "Dakos (barley rusk, the zero-waste hero)",
  ],
  proteinNote:
    "Dried white beans ~15g protein per cooked cup; finished with raw oil and bread, fasoláda clears most of the day's floor with no meat.",
  bonus: false,
  preciousThread: "A bottle of unfiltered new-harvest olive oil to finish every bowl raw.",
  engine: [
    "A big pot of dried white beans, split between fasoláda and gigantes plaki",
    "Good olive oil — the foundation; a generous raw pour finishes every dish",
    "Barley rusks (paximadi) and a loaf — the bread base, stale rusk saved for dakos",
    "Cleaned and stewed horta and lemon, the cool bright base ready all week",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "fasolada — the headline bean pot, finished with raw oil",
      estCalories: 620,
      estProtein: 18,
    },
    {
      day: "Mon",
      dinner: "gigantes-plaki — the big beans baked with tomato and oil",
      estCalories: 660,
      estProtein: 19,
    },
    {
      day: "Tue",
      dinner: "fasolada, the pot deepened on day two, with bread",
      estCalories: 610,
      estProtein: 17,
    },
    {
      day: "Wed",
      dinner: "mavromatika-spanaki — black-eyed peas with spinach and lemon",
      estCalories: 600,
      estProtein: 20,
    },
    {
      day: "Thu",
      dinner: "gigantes-plaki with a side of horta and bread",
      estCalories: 650,
      estProtein: 18,
    },
    {
      day: "Fri",
      dinner: "fasolada again, the cheapest fasting-day bowl, with rusk",
      estCalories: 610,
      estProtein: 17,
    },
    {
      day: "Sat",
      dinner: "dakos — stale barley rusk soaked with tomato, oil, and cheese, the zero-waste finale",
      estCalories: 580,
      estProtein: 16,
    },
  ],
  shopping: [
    { item: "Unfiltered new-harvest olive oil", qty: "1 L", cost: 9.0, spansWeeks: true, note: "the precious thread — finishes every bowl raw, carries the arc" },
    { item: "Dried white beans (cannellini / navy)", qty: "2 lb", cost: 3.0, note: "the bank — fasoláda and the soup" },
    { item: "Dried giant beans (gigantes / large lima)", qty: "1.5 lb", cost: 3.0 },
    { item: "Black-eyed peas (mavromátika)", qty: "1 lb", cost: 1.6 },
    { item: "Barley rusks (paximadi)", qty: "1 bag", cost: 3.5, note: "the rusk base, stale ones become dakos" },
    { item: "Crusty bread / flour for a loaf", qty: "", cost: 1.5 },
    { item: "Canned + fresh tomatoes", qty: "~3 lb", cost: 4.0 },
    { item: "Celery + carrots", qty: "1 bunch / 1 lb", cost: 2.0 },
    { item: "Onions", qty: "~3 lb", cost: 3.0 },
    { item: "Spinach + horta (chicory / dandelion)", qty: "2 bunches", cost: 3.0 },
    { item: "Garlic", qty: "2 heads", cost: 1.0, spansWeeks: true },
    { item: "Lemons", qty: "6", cost: 2.0, spansWeeks: true },
    { item: "Feta or mizithra (for dakos)", qty: "~1/4 lb", cost: 2.5 },
    { item: "Dried oregano + bay", qty: "small", cost: 1.5, spansWeeks: true },
  ],
  firstShopTotal: 30,
  steadyStateWeekly: 18,
};

export const grWeek2Ospria: WeekPlan = {
  slug: "gr-week-2-ospria",
  number: 2,
  cuisine: "greek",
  theme: "Óspria — Lentils & Chickpeas",
  title: "Week 2 — Óspria",
  description:
    "The pulses that carry the fasting calendar. Brown lentils simmered into fakes, chickpeas slow-baked overnight into revithada, those same chickpeas mashed and fried into golden revithokeftedes, and Santorini's silky split-pea fava — the whole legume drawer, one pot at a time.",
  context:
    `The pulses that carry the fasting calendar. Óspria — the family of dried legumes — is what an Orthodox household leans on through Lent and the Wednesday-and-Friday fasts that recur all year: lentils, chickpeas, split peas, all cheap, all storable, all meatless. Fakes is brown-lentil soup, finished, crucially, with a splash of red-wine vinegar that cuts the earthiness and makes the whole bowl sing. Revithada is the Sifnos Sunday dish — chickpeas baked all night in a clay pot in the cooling baker's oven after the bread came out, so dinner cooks while the village sleeps. The leftover chickpeas mash into revithokeftedes, and Santorini's fava (yellow split peas, not the bean) whips to a silk purée under raw oil and onion.`,
  dishes: [
    "Fakés (brown-lentil soup with vinegar)",
    "Revitháda (overnight-baked chickpeas)",
    "Revithokeftédes (chickpea fritters)",
    "Santorini fáva (split-pea purée)",
  ],
  proteinNote: "Lentils ~18g and chickpeas ~15g protein per cooked cup; a bowl of óspria with bread and oil clears the floor with no meat.",
  bonus: false,
  preciousThread: "A bottle of good red-wine vinegar — the splash that finishes the lentils.",
  engine: [
    "A big pot of brown lentils for fakés, and chickpeas soaking for revithada",
    "Good olive oil — the foundation; raw over every bowl of óspria",
    "Barley rusks and bread, the base for sopping up the legume pots",
    "Cleaned horta and lemon, the bright green side ready all week",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "revithada — chickpeas baked slow overnight in the clay pot",
      estCalories: 640,
      estProtein: 19,
    },
    {
      day: "Mon",
      dinner: "fakes — brown-lentil soup finished with red-wine vinegar",
      estCalories: 600,
      estProtein: 18,
    },
    {
      day: "Tue",
      dinner: "santorini-fava — split-pea purée under raw oil and onion, with bread",
      estCalories: 610,
      estProtein: 17,
    },
    {
      day: "Wed",
      dinner: "fakes again, the fasting-day lentil bowl, with rusk",
      estCalories: 600,
      estProtein: 18,
    },
    {
      day: "Thu",
      dinner: "revithada with horta and bread",
      estCalories: 650,
      estProtein: 20,
    },
    {
      day: "Fri",
      dinner: "santorini-fava and a tomato salad on a fasting Friday",
      estCalories: 600,
      estProtein: 16,
    },
    {
      day: "Sat",
      dinner: "revithokeftedes — leftover chickpeas mashed and fried golden, the zero-waste finale",
      estCalories: 640,
      estProtein: 19,
    },
  ],
  shopping: [
    { item: "Good red-wine vinegar", qty: "1 bottle", cost: 4.0, spansWeeks: true, note: "the precious thread — finishes the fakés" },
    { item: "Brown / green lentils (fakés)", qty: "2 lb", cost: 3.2, note: "the bank for the lentil pot" },
    { item: "Dried chickpeas (revithada)", qty: "2 lb", cost: 3.0 },
    { item: "Yellow split peas (Santorini fáva)", qty: "1.5 lb", cost: 2.2 },
    { item: "Onions", qty: "~4 lb", cost: 4.0 },
    { item: "Garlic", qty: "2 heads", cost: 1.0, spansWeeks: true },
    { item: "Canned + fresh tomatoes", qty: "~2 lb", cost: 3.0 },
    { item: "Carrots + celery", qty: "1 lb / 1 bunch", cost: 2.0 },
    { item: "Barley rusks (paximadi)", qty: "1 bag", cost: 3.0 },
    { item: "Crusty bread / flour", qty: "", cost: 1.5 },
    { item: "Horta (chicory / dandelion)", qty: "2 bunches", cost: 3.0 },
    { item: "Lemons", qty: "6", cost: 2.0, spansWeeks: true },
    { item: "Olive oil (top up)", qty: "", cost: 3.0, spansWeeks: true },
    { item: "Dried oregano + bay leaf", qty: "small", cost: 1.0, spansWeeks: true },
  ],
  firstShopTotal: 26,
  steadyStateWeekly: 16,
};

export const grWeek3Ladera: WeekPlan = {
  slug: "gr-week-3-ladera",
  number: 3,
  cuisine: "greek",
  theme: "Ladera — Oil-braised Vegetables",
  title: "Week 3 — Ladera",
  description:
    "The most Greek way to cook a vegetable. Whatever the garden gives — green beans, summer vegetables, okra, peas — braised slow and soft in a flood of olive oil until it is sweet and silken, eaten warm or at room temperature with bread and feta.",
  context:
    `The most Greek way to cook a vegetable. Ladera — from ládi, oil — are dishes braised slow and soft in a flood of olive oil until the vegetable turns sweet, collapsed, and silken: fasolákia ládera (green beans in tomato), briám (the oven-roasted summer-vegetable medley), bámies (okra), arakás látheros (peas with dill). They are deliberately meatless and dairy-free, so they double as fasting food, and they are eaten warm or, better, at room temperature so the oil and tomato settle into the vegetable. Greeks call this lithrá — eating the oil itself as nourishment, the way other cultures eat fat from meat. The vegetables alone are light on protein, so the table pairs every ladera with feta and a bean dish or bread to bring the day up to the floor.`,
  dishes: [
    "Fasolákia ládera (oil-braised green beans)",
    "Briám (roasted summer vegetables)",
    "Bámies (okra in tomato)",
    "Arakás látheros (peas with dill)",
  ],
  proteinNote: "Vegetables alone are light; the day leans on feta and a side of beans or rusk to clear the floor, the classic ladera pairing.",
  bonus: false,
  preciousThread: "A jar of brined capers and good olives to scatter over the braises.",
  engine: [
    "Good olive oil — the foundation, and the whole point of ladera; braise generously",
    "A pot of dried beans alongside, the protein the vegetables can't carry alone",
    "Barley rusks and bread to sop the oil and tomato",
    "Cleaned horta and lemon, plus a wedge of feta, ready to plate all week",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "briam — summer vegetables roasted slow in olive oil, with feta and bread",
      estCalories: 640,
      estProtein: 16,
    },
    {
      day: "Mon",
      dinner: "fasolakia-ladera — green beans braised in tomato and oil, with feta",
      estCalories: 620,
      estProtein: 15,
    },
    {
      day: "Tue",
      dinner: "bamies — okra braised in tomato, with bread and beans on the side",
      estCalories: 630,
      estProtein: 17,
    },
    {
      day: "Wed",
      dinner: "arakas-latheros — peas with dill and oil, with feta and rusk",
      estCalories: 610,
      estProtein: 15,
    },
    {
      day: "Thu",
      dinner: "briam again with a side of white beans for protein",
      estCalories: 650,
      estProtein: 18,
    },
    {
      day: "Fri",
      dinner: "fasolakia-ladera on a fasting Friday, with bread and olives",
      estCalories: 600,
      estProtein: 14,
    },
    {
      day: "Sat",
      dinner: "a ladera platter — leftover briam, beans, and okra folded together with feta, the zero-waste finale",
      estCalories: 650,
      estProtein: 17,
    },
  ],
  shopping: [
    { item: "Brined capers + good olives", qty: "1 jar each", cost: 4.0, spansWeeks: true, note: "the precious thread — scattered over the braises" },
    { item: "Olive oil (ladera drinks oil)", qty: "1 L", cost: 8.0, spansWeeks: true, note: "the foundation, and the point of the week" },
    { item: "Green beans (fasolákia)", qty: "1.5 lb", cost: 3.0 },
    { item: "Okra (bámies)", qty: "1 lb", cost: 2.5 },
    { item: "Peas (arakás)", qty: "1 lb", cost: 2.0 },
    { item: "Zucchini + eggplant + peppers (briám)", qty: "~3 lb", cost: 4.0 },
    { item: "Potatoes", qty: "~2 lb", cost: 1.5 },
    { item: "Canned + fresh tomatoes", qty: "~3 lb", cost: 4.0 },
    { item: "Onions + garlic", qty: "~3 lb / 2 heads", cost: 3.5 },
    { item: "Feta", qty: "~1/2 lb", cost: 3.5, note: "the protein partner for every ladera" },
    { item: "Dried white beans (the protein side)", qty: "1 lb", cost: 1.5 },
    { item: "Barley rusks + bread", qty: "1 bag / loaf", cost: 3.0 },
    { item: "Fresh dill + lemons", qty: "1 bunch / 4", cost: 2.5, spansWeeks: true },
  ],
  firstShopTotal: 32,
  steadyStateWeekly: 19,
};

export const grWeek4Gemista: WeekPlan = {
  slug: "gr-week-4-gemista",
  number: 4,
  cuisine: "greek",
  theme: "Gemistá & Dolmádes",
  title: "Week 4 — Gemistá",
  description:
    "The week of stuffed things. Summer vegetables hollowed and packed with herbed rice, vine leaves rolled tight around the same filling, cabbage leaves wrapped into bundles — humble rice stretched with herbs, pine nuts, and currants into something that feels like a feast.",
  context:
    `The week of stuffed things. Gemistá — tomatoes, peppers, and zucchini hollowed out and packed with rice scented with mint, dill, and parsley, then baked slow in oil until the tops caramelize — is the Sunday table of the Greek summer, eaten at room temperature. Dolmadákia are the same idea rolled small in vine leaves, lemony and tight; lahanodolmádes wrap the filling in cabbage for winter. The genius is economy: a little rice and a fistful of herbs, stretched by the vegetable shells, feeds a family. The nistísimo (fasting) version skips the meat entirely and leans on the pantry's two small luxuries — pine nuts and currants — folded into the rice for richness and a sweet note that turns plain rice into something festive. The hollowed-out vegetable flesh goes back into the pan, so nothing is wasted.`,
  dishes: [
    "Gemistá (stuffed tomatoes + peppers)",
    "Dolmadákia (rolled vine leaves)",
    "Lahanodolmádes (cabbage rolls)",
    "Herbed rice with pine nuts + currants",
  ],
  proteinNote: "Rice and herbs are light; the day leans on feta, a side of beans, and the pine nuts to bring it up to the floor.",
  bonus: false,
  preciousThread: "Pine nuts and currants, folded into the rice for richness.",
  engine: [
    "A big pot of herbed rice filling — mint, dill, parsley, pine nuts, currants — for everything stuffed",
    "Good olive oil — the foundation; the gemistá bake and rest in it",
    "Vine leaves blanched and a cabbage cored, ready to roll",
    "Barley rusks, bread, and a pot of beans, the protein and starch the rice can't carry alone",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "gemista — tomatoes and peppers stuffed with herbed rice, baked in oil",
      estCalories: 640,
      estProtein: 16,
    },
    {
      day: "Mon",
      dinner: "dolmadakia — vine leaves rolled small and lemony, with bread and feta",
      estCalories: 600,
      estProtein: 15,
    },
    {
      day: "Tue",
      dinner: "gemista again, even better at room temperature, with a bean side",
      estCalories: 650,
      estProtein: 18,
    },
    {
      day: "Wed",
      dinner: "lahanodolmades — cabbage rolls in a lemon broth",
      estCalories: 620,
      estProtein: 16,
    },
    {
      day: "Thu",
      dinner: "dolmadakia with horta and feta",
      estCalories: 610,
      estProtein: 17,
    },
    {
      day: "Fri",
      dinner: "gemista on a fasting Friday, the meatless rice version with bread",
      estCalories: 620,
      estProtein: 15,
    },
    {
      day: "Sat",
      dinner: "a stuffed-vegetable platter — the last gemistá, dolmádes, and the rice scrapings baked together, the zero-waste finale",
      estCalories: 640,
      estProtein: 17,
    },
  ],
  shopping: [
    { item: "Pine nuts + currants", qty: "small each", cost: 4.5, spansWeeks: true, note: "the precious thread — richness folded into the rice" },
    { item: "Medium-grain rice", qty: "2 lb", cost: 2.5, note: "the filling base" },
    { item: "Large tomatoes + bell peppers (to stuff)", qty: "~4 lb", cost: 5.0 },
    { item: "Zucchini (to stuff)", qty: "~1.5 lb", cost: 2.0 },
    { item: "Vine leaves (jarred or fresh)", qty: "1 jar", cost: 3.5 },
    { item: "Green cabbage (lahanodolmádes)", qty: "1 head", cost: 2.0 },
    { item: "Fresh mint + dill + parsley", qty: "1 bunch each", cost: 3.0 },
    { item: "Onions + garlic", qty: "~3 lb / 2 heads", cost: 3.0 },
    { item: "Feta", qty: "~1/4 lb", cost: 2.5 },
    { item: "Dried white beans (protein side)", qty: "1 lb", cost: 1.5 },
    { item: "Barley rusks + bread", qty: "1 bag / loaf", cost: 3.0 },
    { item: "Lemons", qty: "6", cost: 2.0, spansWeeks: true },
    { item: "Olive oil (top up)", qty: "", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 30,
  steadyStateWeekly: 18,
};

export const grWeek5Horta: WeekPlan = {
  slug: "gr-week-5-horta",
  number: 5,
  cuisine: "greek",
  theme: "Hórta & Pites — Greens",
  title: "Week 5 — Hórta & Pites",
  description:
    "The week of wild greens. Foraged hórta boiled and dressed with oil and lemon, the same greens folded into a savory pie under crackling phyllo, or simmered with rice into spanakórizo and prasórizo — the hillside and the garden, eaten as the meal itself.",
  context:
    `The week of wild greens. Hórta — the wild greens that grow free on every Greek hillside, dandelion, chicory, amaranth, sow-thistle — are gathered, boiled until tender, and dressed simply with olive oil and a hard squeeze of lemon: the most ancient Greek food there is, and still a weekly meal. The same greens, chopped and wilted, fill spanakópita under crackling phyllo, or simmer with rice into spanakórizo (spinach) and prasórizo (leek), one-pot greens-and-rice dinners. This is foraging as cuisine — knowing which weeds are dinner is grandmother-knowledge passed down on hillside walks, and it costs nothing but the walk. The greens are light on protein, so a wedge of good feta crumbled over the pie or the rice — the week's one luxury — anchors the plate.`,
  dishes: [
    "Hórta vrastá (boiled greens, oil + lemon)",
    "Spanakópita (greens pie in phyllo)",
    "Spanakórizo (spinach + rice)",
    "Prasórizo (leek + rice)",
  ],
  proteinNote: "Greens are light; a wedge of feta over the pie or rice and a side of beans bring the day to the floor.",
  bonus: false,
  preciousThread: "A wedge of good feta to crumble over the greens and the pie.",
  engine: [
    "A big haul of cleaned and boiled hórta — the week's constant, ready to dress, stuff, or simmer",
    "Good olive oil and lemon — the foundation; the dressing the greens live on",
    "A batch of phyllo (or one rested dough) for spanakópita",
    "Barley rusks, bread, and a small pot of beans, the starch and protein alongside",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "spanakopita — greens and feta baked under crackling phyllo",
      estCalories: 660,
      estProtein: 20,
    },
    {
      day: "Mon",
      dinner: "horta-vrasta — boiled greens with oil and lemon, with beans and bread",
      estCalories: 600,
      estProtein: 17,
    },
    {
      day: "Tue",
      dinner: "spanakorizo — spinach simmered with rice, with feta",
      estCalories: 630,
      estProtein: 18,
    },
    {
      day: "Wed",
      dinner: "spanakopita again, the slice that's even better cold, with horta",
      estCalories: 650,
      estProtein: 20,
    },
    {
      day: "Thu",
      dinner: "prasorizo — leeks and rice with dill and lemon, with feta",
      estCalories: 620,
      estProtein: 16,
    },
    {
      day: "Fri",
      dinner: "horta-vrasta on a fasting Friday, oil and lemon, with rusk and olives",
      estCalories: 580,
      estProtein: 14,
    },
    {
      day: "Sat",
      dinner: "a greens pie from the week's odds — the last horta, rice, and feta wrapped in phyllo, the zero-waste finale",
      estCalories: 660,
      estProtein: 20,
    },
  ],
  shopping: [
    { item: "Good feta", qty: "~3/4 lb", cost: 5.0, note: "the precious thread — over the greens and the pie" },
    { item: "Hórta (dandelion / chicory / amaranth)", qty: "3 bunches", cost: 4.5, note: "the foraged green week" },
    { item: "Spinach", qty: "2 lb", cost: 3.0 },
    { item: "Leeks (prasórizo)", qty: "3 large", cost: 2.5 },
    { item: "Phyllo dough", qty: "1 lb box", cost: 3.0 },
    { item: "Medium-grain rice", qty: "1.5 lb", cost: 2.0 },
    { item: "Spring onions + fresh dill + parsley", qty: "1 bunch each", cost: 3.0 },
    { item: "Onions + garlic", qty: "~2 lb / 2 heads", cost: 2.5 },
    { item: "Dried white beans (protein side)", qty: "1 lb", cost: 1.5 },
    { item: "Barley rusks + bread", qty: "1 bag / loaf", cost: 3.0 },
    { item: "Lemons", qty: "8", cost: 2.5, spansWeeks: true },
    { item: "Olive oil (top up)", qty: "", cost: 3.0, spansWeeks: true },
    { item: "Olives (for the fasting days)", qty: "small jar", cost: 1.5, spansWeeks: true },
  ],
  firstShopTotal: 31,
  steadyStateWeekly: 19,
};

export const grWeek6Avgolemono: WeekPlan = {
  slug: "gr-week-6-avgolemono",
  number: 6,
  cuisine: "greek",
  theme: "Avgolémono — Egg & Lemon",
  title: "Week 6 — Avgolémono",
  description:
    "The week the fast breaks gently. Eggs whisked with lemon and tempered into hot broth make the silky, tart sauce that turns a thin soup or a few meatballs into something rich — a little egg and a little chicken stretched across the whole week.",
  context:
    `The week the fast breaks gently. Avgolémono — eggs whisked with lemon juice, then tempered spoon by spoon with hot broth so they thicken without scrambling — is the technique that defines Greek comfort food, turning the thinnest broth silky and tart. Soúpa avgolémono is chicken, rice, and that sauce; youvarlákia are little rice-and-meat meatballs poached and finished in it; kotópoulo frikasé braises chicken with greens under the same lemony cloak. This is fasting-broken cooking — eggs and a little meat are exactly what an Orthodox household returns to after a fast, which is why avgolémono is the taste of Sunday and of recovery from illness. The economy still holds: one chicken and a few eggs, stretched by rice and broth and lemon, carry the whole week, and the carcass becomes the next day's stock.`,
  dishes: [
    "Soúpa avgolémono (chicken-rice-egg soup)",
    "Youvarlákia (meatballs in egg-lemon)",
    "Kotópoulo frikasé (chicken + greens)",
    "Egg-lemon over rice and greens",
  ],
  proteinNote: "Eggs, a little chicken, and the rice carry the protein; avgolémono weeks clear the floor comfortably at ~25–30g a bowl.",
  bonus: false,
  preciousThread: "A few eggs and a little chicken — the gentle break from the fast.",
  engine: [
    "A pot of chicken broth from one bird, the base for soup and frikasé, carcass saved for stock",
    "Good olive oil and a bowl of lemons — the foundation; lemon is half of every avgolémono",
    "A bowl of eggs, the other half of the sauce, ready to whisk and temper",
    "Barley rusks, bread, and prepped horta, the starch and green alongside",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "soupa-avgolemono — chicken, rice, and the silky egg-lemon sauce",
      estCalories: 660,
      estProtein: 30,
    },
    {
      day: "Mon",
      dinner: "youvarlakia — rice-and-meat meatballs poached in egg-lemon broth",
      estCalories: 690,
      estProtein: 29,
    },
    {
      day: "Tue",
      dinner: "kotopoulo-fricassee — chicken braised with greens under egg-lemon",
      estCalories: 700,
      estProtein: 31,
    },
    {
      day: "Wed",
      dinner: "soupa-avgolemono again from the deepened broth, with bread",
      estCalories: 650,
      estProtein: 28,
    },
    {
      day: "Thu",
      dinner: "youvarlakia with horta and lemon on the side",
      estCalories: 680,
      estProtein: 28,
    },
    {
      day: "Fri",
      dinner: "a meatless soupa-avgolemono — rice and greens under egg-lemon, with bread",
      estCalories: 620,
      estProtein: 22,
    },
    {
      day: "Sat",
      dinner: "egg-lemon soup from the carcass stock and the week's last rice and chicken, the zero-waste finale",
      estCalories: 650,
      estProtein: 27,
    },
  ],
  shopping: [
    { item: "Eggs", qty: "1.5 dozen", cost: 5.0, note: "the precious thread — half of every avgolémono" },
    { item: "Whole chicken (soup, frikasé, stock)", qty: "~3 1/2 lb bird", cost: 7.0, note: "the precious thread — one bird, the whole week" },
    { item: "Ground meat (youvarlákia)", qty: "~3/4 lb", cost: 4.0 },
    { item: "Medium-grain rice", qty: "2 lb", cost: 2.5 },
    { item: "Lemons", qty: "1 dozen", cost: 4.0, spansWeeks: true, note: "the other half of the sauce" },
    { item: "Onions + garlic", qty: "~2 lb / 1 head", cost: 2.5 },
    { item: "Carrots + celery (for broth)", qty: "1 lb / 1 bunch", cost: 2.0 },
    { item: "Horta + lettuce / greens (frikasé)", qty: "2 bunches", cost: 3.0 },
    { item: "Fresh dill + parsley", qty: "1 bunch each", cost: 2.0 },
    { item: "Barley rusks + bread", qty: "1 bag / loaf", cost: 3.0 },
    { item: "Olive oil (top up)", qty: "", cost: 3.0, spansWeeks: true },
    { item: "Dried white beans (a meatless-day side)", qty: "1/2 lb", cost: 0.8 },
  ],
  firstShopTotal: 35,
  steadyStateWeekly: 21,
};

export const grWeek7Psari: WeekPlan = {
  slug: "gr-week-7-psari",
  number: 7,
  cuisine: "greek",
  theme: "Psári — The Sea",
  title: "Week 7 — Psári",
  description:
    "The finale at the water's edge. Small, cheap, whole fish — fried crisp by the handful, salt cod with a fist of garlic skordaliá, simmered into a lemony fisherman's soup, or baked with tomato and herbs — the abundance of a country that is mostly coastline.",
  context:
    `The finale at the water's edge. Greece is mostly coastline and islands, and the cheapest fish were never the prized ones but the small fry — marídes (picarel) and gávros (anchovy) and sardéles (sardines), sold by the kilo and eaten whole. Marídes tiganités are floured and fried crisp by the handful and eaten head and all; bakaliáros skordaliá pairs fried salt cod with a punishing fist of garlic-and-bread skordaliá, the Independence-Day dish; psarósoupa simmers the bony fish nobody else wants with potato and lemon into a clear, restorative soup; sardéles sto foúrno bake under tomato, oregano, and oil. This is fasting food too on the days fish is allowed, and zero-waste by nature — the whole fish goes in, heads and bones make the soup, the frying oil season the next pan. A cheap fish, oil, lemon, and bread: the oldest Mediterranean dinner there is.`,
  dishes: [
    "Marídes tiganités (fried small fish)",
    "Bakaliáros skordaliá (salt cod + garlic sauce)",
    "Psarósoupa (fisherman's lemon soup)",
    "Sardéles sto foúrno (baked sardines)",
  ],
  proteinNote: "The small fish carry it — fried, baked, or in soup, a plate of psári clears the floor easily at ~25–30g.",
  bonus: false,
  preciousThread: "The fresh small fish — marídes, sardines, a piece of salt cod.",
  engine: [
    "The fish, cleaned and split — small fry for frying, salt cod soaking, bony fish for soup stock",
    "Good olive oil and lemons — the foundation; the dressing and the frying fat",
    "A batch of skordaliá — garlic, bread, and oil whipped thick, for the cod",
    "Barley rusks, bread, and prepped horta, the starch and green alongside the fish",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "bakaliaros-skordalia — fried salt cod with a fist of garlic skordaliá and horta",
      estCalories: 700,
      estProtein: 30,
    },
    {
      day: "Mon",
      dinner: "marides-tiganites — small fish floured and fried crisp, eaten whole, with lemon",
      estCalories: 660,
      estProtein: 27,
    },
    {
      day: "Tue",
      dinner: "psarosoupa — bony fish simmered with potato and lemon into a clear soup",
      estCalories: 640,
      estProtein: 28,
    },
    {
      day: "Wed",
      dinner: "sardeles-sto-fourno — sardines baked under tomato, oregano, and oil",
      estCalories: 670,
      estProtein: 29,
    },
    {
      day: "Thu",
      dinner: "marides-tiganites again with a side of beans and bread",
      estCalories: 670,
      estProtein: 28,
    },
    {
      day: "Fri",
      dinner: "bakaliaros-skordalia, the fasting-day fish, with the last of the skordaliá",
      estCalories: 690,
      estProtein: 29,
    },
    {
      day: "Sat",
      dinner: "psarosoupa from the week's heads and bones and the last fish, with rusk and lemon, the zero-waste finale",
      estCalories: 650,
      estProtein: 27,
    },
  ],
  shopping: [
    { item: "Fresh small fish (marídes / sardines / anchovy)", qty: "~3 lb", cost: 9.0, note: "the precious thread — the abundance of the coast" },
    { item: "Salt cod (bakaliáros)", qty: "~1 lb", cost: 6.0, note: "soaked for skordaliá day" },
    { item: "Bony fish / fish frames (psarósoupa)", qty: "~2 lb", cost: 3.5 },
    { item: "Garlic (for skordaliá)", qty: "3 heads", cost: 1.5, spansWeeks: true, note: "skordaliá takes a fistful" },
    { item: "Stale bread / potatoes (skordaliá base)", qty: "loaf / 1 lb", cost: 1.5 },
    { item: "Potatoes (psarósoupa)", qty: "~2 lb", cost: 1.5 },
    { item: "Flour (for dredging)", qty: "1 lb", cost: 1.0 },
    { item: "Canned + fresh tomatoes", qty: "~2 lb", cost: 3.0 },
    { item: "Onions + carrots + celery", qty: "~3 lb", cost: 3.0 },
    { item: "Horta (the green side)", qty: "2 bunches", cost: 3.0 },
    { item: "Lemons", qty: "1 dozen", cost: 4.0, spansWeeks: true, note: "lemon over every fish" },
    { item: "Barley rusks + bread", qty: "1 bag / loaf", cost: 3.0 },
    { item: "Olive oil (frying + finishing)", qty: "top up", cost: 4.0, spansWeeks: true },
    { item: "Dried oregano + bay", qty: "small", cost: 1.0, spansWeeks: true },
  ],
  firstShopTotal: 36,
  steadyStateWeekly: 22,
};

export const greekWeeks: WeekPlan[] = [
  grWeek1Fasolada,
  grWeek2Ospria,
  grWeek3Ladera,
  grWeek4Gemista,
  grWeek5Horta,
  grWeek6Avgolemono,
  grWeek7Psari,
];
