import type { WeekPlan } from "../types";
import { mxWeek1Masa } from "./mx-week-1-masa";

// Challenge #2 — Mexico: La Cocina del Maíz.
// The full seven-week arc, every week built out into an executable WeekPlan
// (engine + 7 days + costed shopping list). Week 1 (Masa) lives in
// ./mx-week-1-masa.ts; weeks 2–7 are below. These are the curated, pregenerated
// defaults — the AI menu generator lets users compose their own variations on
// top of the same recipe pool. cuisine is "mexican"; the engine is
// cuisine-agnostic, so these slot into the shared content arrays, tagged by cuisine.

export const week2Frijoles: WeekPlan = {
  slug: "mx-week-2-frijoles",
  number: 2,
  cuisine: "mexican",
  theme: "Frijoles",
  title: "Week 2 — Frijoles",
  description:
    "The other half of the sacred pair and the protein engine of the whole challenge. A dollar pot of beans, simmered slow with epazote, pays out all week — cheapest near-complete protein there is, eaten with corn.",
  context:
    `The other half of the sacred pair, and the protein engine of the whole challenge. A pot of frijoles de la olla — dried beans simmered slow with onion and epazote — costs about a dollar and gives roughly 12–15g of protein per cup, the cheapest near-complete protein there is when eaten with corn. Refried in a little lard, or brothy as frijoles charros with a scrap of pork, the bean pot is your bank; it pays out all week. Day-two beans become refritos and the cooking liquid becomes soup — nothing is thrown away.`,
  dishes: [
    "Frijoles de la olla (the pot)",
    "Frijoles refritos (day-two beans, refried)",
    "Frijoles charros (brothy, with pork scraps)",
    "Molletes (beans on bread, broiled with cheese)",
  ],
  proteinNote: "Beans ~12–15g protein per cup; with a tortilla, a complete protein.",
  bonus: false,
  preciousThread: "A little lard or a knuckle of bacon to enrich the pot.",
  engine: [
    "A big pot of frijoles de la olla (the bean bank for the whole week)",
    "Half the pot reserved and mashed into frijoles-refritos",
    "A double batch of corn-tortillas off the comal",
    "A jar of salsa-roja-asada to dress beans, eggs, and molletes",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      breakfast: "huevos-a-la-mexicana with warm corn-tortillas",
      lunch: "frijoles-de-la-olla, brothy, with tortillas and queso fresco",
      dinner: "tacos of frijoles-refritos, queso fresco, salsa-roja-asada",
      estCalories: 2040,
      estProtein: 106,
    },
    {
      day: "Mon",
      breakfast: "frijoles-refritos with an egg and tortilla",
      lunch: "molletes — refried beans on a roll, broiled with cheese",
      dinner: "frijoles-charros with tortillas",
      estCalories: 2010,
      estProtein: 104,
    },
    {
      day: "Tue",
      breakfast: "huevos-rancheros over a bean-smeared tortilla",
      lunch: "leftover frijoles-charros + warm tortillas",
      dinner: "quesadillas-de-maiz with frijoles-refritos and salsa-verde",
      estCalories: 2000,
      estProtein: 102,
    },
    {
      day: "Wed",
      breakfast: "frijoles-refritos, egg, and salsa-roja-asada on tortilla",
      lunch: "bean-and-cheese tacos with tortillas",
      dinner: "enfrijoladas — tortillas folded in a bean-broth sauce, queso fresco, crema",
      estCalories: 2030,
      estProtein: 105,
    },
    {
      day: "Thu",
      breakfast: "huevos-a-la-mexicana with a side of refried beans",
      lunch: "molletes again — beans, cheese, pico on a broiled roll",
      dinner: "frijoles-de-la-olla soup from the second pot, with tortillas and egg",
      estCalories: 1990,
      estProtein: 101,
    },
    {
      day: "Fri",
      breakfast: "frijoles-refritos with egg and tortilla",
      lunch: "quesadillas-de-maiz with beans and salsa-verde",
      dinner: "frijoles-puercos — refried beans enriched with a scrap of chorizo, scooped with tortillas",
      estCalories: 2050,
      estProtein: 107,
    },
    {
      day: "Sat",
      breakfast: "huevos-rancheros with beans",
      lunch: "molletes with the last of the cheese",
      dinner: "enfrijoladas finale — the last tortillas folded in the last of the bean broth, egg on top, nothing wasted",
      estCalories: 2040,
      estProtein: 106,
    },
  ],
  shopping: [
    { item: "Dried pinto or black beans", qty: "3 lb", cost: 4.0, note: "the bean bank — the whole week runs on this" },
    { item: "Masa harina (corn)", qty: "~4 lb bag", cost: 4.5 },
    {
      item: "Eggs",
      qty: "2 dozen",
      cost: 8.0,
      note: "stacks the protein on top of the beans",
    },
    { item: "Bolillo / telera rolls (for molletes)", qty: "6–8", cost: 3.0 },
    { item: "Queso fresco", qty: "~½ lb", cost: 4.0, spansWeeks: true },
    { item: "Oaxaca cheese / quesillo", qty: "~½ lb", cost: 4.0, spansWeeks: true },
    { item: "Tomatoes", qty: "~3 lb", cost: 4.0 },
    { item: "Tomatillos", qty: "1 lb", cost: 2.0 },
    {
      item: "Dried chiles (guajillo, ancho, árbol)",
      qty: "a few of each",
      cost: 4.0,
      spansWeeks: true,
    },
    { item: "White onions", qty: "~3 lb", cost: 3.0 },
    { item: "Garlic", qty: "2 heads", cost: 2.0, spansWeeks: true },
    { item: "Serrano / jalapeño chiles", qty: "a handful", cost: 1.5 },
    { item: "Cilantro + epazote", qty: "for the pot", cost: 2.0 },
    { item: "Crema", qty: "1 small", cost: 3.0 },
    { item: "Chorizo / bacon (scrap, for charros & puercos)", qty: "~¼ lb", cost: 2.5 },
    { item: "Lard or oil", qty: "", cost: 5.0, spansWeeks: true },
  ],
  firstShopTotal: 58,
  steadyStateWeekly: 46,
};

export const week3Chiles: WeekPlan = {
  slug: "mx-week-3-chiles",
  number: 3,
  cuisine: "mexican",
  theme: "Chiles & Salsas",
  title: "Week 3 — Chiles & Salsas",
  description:
    "The secret of how the poor ate well, not just enough. Toasted dried chiles and charred tomatoes ground in the molcajete turn a plain tortilla and beans into something you crave — almost free, infinitely variable.",
  context:
    `The secret of how the poor ate well, not just enough. Chile — fresh and dried — is the engine of flavor that turns a plain tortilla and beans into something you crave. Toast dried chiles (guajillo, ancho, chile de árbol, pasilla), char tomatoes and tomatillos, and grind them in the molcajete (volcanic mortar): salsa roja, salsa verde, salsa macha. Almost free, endlessly variable, and itself the great anti-waste tool — a good salsa makes any leftover delicious again.`,
  dishes: [
    "Salsa roja asada (charred tomato + chile de árbol)",
    "Salsa verde (tomatillo)",
    "Salsa macha (toasted chile-and-seed oil)",
    "Enchiladas / entomatadas built on the salsas",
  ],
  proteinNote: "Chiles carry the legume/egg base of the other weeks.",
  bonus: false,
  preciousThread: "A small bag of good dried chiles (guajillo, ancho, árbol).",
  engine: [
    "A big pot of frijoles de la olla (the bean bank for the week)",
    "A jar of salsa roja asada (charred tomato + chile de árbol)",
    "A jar of salsa verde (tomatillo)",
    "A jar of salsa macha (toasted chile-and-seed oil for spooning over everything)",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      breakfast: "huevos-a-la-mexicana",
      lunch: "quesadillas-de-maiz with the fresh salsa-verde",
      dinner: "enchiladas rojas — tortillas dipped in salsa-roja-asada, filled with frijoles-refritos and queso fresco",
      estCalories: 2050,
      estProtein: 106,
    },
    {
      day: "Mon",
      breakfast: "chilaquiles-rojos with an egg",
      lunch: "frijoles-de-la-olla + warm tortillas, spoonful of salsa macha",
      dinner: "entomatadas — tortillas folded in salsa-roja-asada with cheese + a fried egg",
      estCalories: 2010,
      estProtein: 103,
    },
    {
      day: "Tue",
      breakfast: "huevos-rancheros over salsa-roja-asada",
      lunch: "quesadillas-de-maiz with salsa-verde",
      dinner: "enchiladas verdes — tortillas in salsa-verde, frijoles-refritos, queso fresco, crema",
      estCalories: 2000,
      estProtein: 102,
    },
    {
      day: "Wed",
      breakfast: "eggs scrambled with salsa macha + tortillas",
      lunch: "frijoles-refritos tacos with salsa-roja-asada",
      dinner: "huevos-a-la-mexicana with charro-style beans and tortillas",
      estCalories: 2030,
      estProtein: 105,
    },
    {
      day: "Thu",
      breakfast: "chilaquiles (verdes) with an egg, built on salsa-verde",
      lunch: "bean-and-cheese quesadillas-de-maiz, salsa macha on the side",
      dinner: "frijoles-charros with tortillas and a spoon of salsa-roja-asada",
      estCalories: 1990,
      estProtein: 104,
    },
    {
      day: "Fri",
      breakfast: "huevos en salsa verde with beans and tortillas",
      lunch: "molletes — beans on a roll, broiled with cheese, salsa-roja-asada on top",
      dinner: "enmoladas-style entomatadas in salsa-roja-asada with egg + queso fresco",
      estCalories: 2040,
      estProtein: 103,
    },
    {
      day: "Sat",
      breakfast: "huevos-rancheros with the last of the salsa-verde",
      lunch: "frijoles-refritos + tortillas, salsa macha",
      dinner: "chilaquiles-rojos for dinner — the last tortillas drowned in the last of the salsa-roja-asada, egg and cheese on top, nothing wasted",
      estCalories: 2050,
      estProtein: 106,
    },
  ],
  shopping: [
    {
      item: "Dried chiles (guajillo, ancho, árbol, pasilla)",
      qty: "a good handful of each",
      cost: 5.0,
      spansWeeks: true,
      note: "the flavor engine — toasted for every salsa",
    },
    { item: "Masa harina (corn)", qty: "~3 lb bag", cost: 3.5 },
    { item: "Dried pinto or black beans", qty: "2 lb", cost: 2.5 },
    {
      item: "Eggs",
      qty: "2 dozen",
      cost: 8.0,
      note: "the protein backbone this week",
    },
    { item: "Tomatoes (for asada salsas)", qty: "~3 lb", cost: 4.0 },
    { item: "Tomatillos", qty: "~2 lb", cost: 3.5 },
    { item: "Queso fresco", qty: "~½ lb", cost: 4.0, spansWeeks: true },
    { item: "Oaxaca cheese / quesillo", qty: "~½ lb", cost: 4.5, spansWeeks: true },
    { item: "White onions", qty: "~3 lb", cost: 3.0 },
    { item: "Garlic", qty: "2 heads", cost: 2.0, spansWeeks: true },
    { item: "Serrano / jalapeño chiles", qty: "a handful", cost: 1.5 },
    {
      item: "Sesame + peanuts (for salsa macha)",
      qty: "small bags",
      cost: 3.0,
      spansWeeks: true,
    },
    { item: "Oil (for salsa macha + comal)", qty: "", cost: 4.5, spansWeeks: true },
    { item: "Cilantro + epazote", qty: "", cost: 2.0 },
    { item: "Limes", qty: "6", cost: 2.0 },
    { item: "Crema", qty: "1 small", cost: 3.0 },
  ],
  firstShopTotal: 58,
  steadyStateWeekly: 46,
};

export const week4Huevos: WeekPlan = {
  slug: "mx-week-4-huevos",
  number: 4,
  cuisine: "mexican",
  theme: "Huevos",
  title: "Week 4 — Huevos",
  description:
    "The cheap-protein bridge — the backyard hen feeds the Mexican kitchen too. With beans and a tortilla, an egg breakfast clears the protein floor before the day has started.",
  context:
    `The cheap-protein bridge, exactly as eggs are in the Italian arc. The backyard hen feeds the Mexican kitchen too: huevos a la mexicana (scrambled with the three colors of the flag — white onion, green chile, red tomato), huevos rancheros over tortilla and salsa, huevos en salsa, and migas built from stale tortilla chips. With beans and a tortilla, an egg breakfast clears the protein floor before the day has even started — the recovery week of this arc.`,
  dishes: [
    "Huevos a la mexicana (scrambled with tomato, onion, chile)",
    "Huevos rancheros (fried eggs over tortilla and salsa)",
    "Huevos en salsa verde",
    "Migas (stale tortilla scrambled into the eggs)",
  ],
  proteinNote: "Eggs — the floor is trivially met, as in the Italian egg week.",
  bonus: false,
  preciousThread: "A little crema or chorizo to gild it.",
  engine: [
    "A big pot of frijoles de la olla (the bean bank, refried as the week goes)",
    "A jar of salsa roja asada and a jar of salsa verde (the egg sauces)",
    "A stack of fresh tortillas — and totopos from the rest, for migas and chilaquiles",
    "Tomato, onion, and chile prepped for the week's huevos a la mexicana",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      breakfast: "huevos-a-la-mexicana with warm tortillas",
      lunch: "quesadillas-de-maiz with salsa-verde",
      dinner: "huevos-rancheros over frijoles-refritos and salsa-roja-asada",
      estCalories: 2050,
      estProtein: 110,
    },
    {
      day: "Mon",
      breakfast: "huevos-a-la-mexicana with frijoles-refritos and tortillas",
      lunch: "bean-and-egg tacos with salsa-verde",
      dinner: "huevos en salsa verde over rice and beans",
      estCalories: 2000,
      estProtein: 106,
    },
    {
      day: "Tue",
      breakfast: "huevos-rancheros over tortilla and salsa",
      lunch: "leftover beans + warm tortillas + a fried egg",
      dinner: "huevos en salsa roja with frijoles-refritos and tortillas",
      estCalories: 2010,
      estProtein: 104,
    },
    {
      day: "Wed",
      breakfast: "migas — totopos scrambled into the eggs with salsa",
      lunch: "quesadillas-de-maiz with a fried egg and salsa-verde",
      dinner: "huevos-a-la-mexicana with charro-style beans and tortillas",
      estCalories: 2020,
      estProtein: 108,
    },
    {
      day: "Thu",
      breakfast: "huevos en salsa verde with tortillas",
      lunch: "molletes with a fried egg on top",
      dinner: "huevos-rancheros over beans, salsa-roja-asada, and queso fresco",
      estCalories: 1990,
      estProtein: 105,
    },
    {
      day: "Fri",
      breakfast: "huevos-a-la-mexicana with frijoles-refritos",
      lunch: "egg-and-bean tacos with salsa-verde and crema",
      dinner: "huevos en salsa roja over the last of the beans and tortillas",
      estCalories: 2030,
      estProtein: 107,
    },
    {
      day: "Sat",
      breakfast: "huevos-rancheros over tortilla and salsa",
      lunch: "esquites + a fried-egg quesadilla",
      dinner: "migas for dinner — the last totopos scrambled into eggs, nothing wasted",
      estCalories: 2040,
      estProtein: 108,
    },
  ],
  shopping: [
    {
      item: "Eggs",
      qty: "3 dozen",
      cost: 12.0,
      note: "the protein backbone this week — the whole register runs on huevos",
    },
    { item: "Masa harina (corn) / tortillas", qty: "~3 lb", cost: 3.5 },
    { item: "Dried pinto or black beans", qty: "2 lb", cost: 2.5 },
    { item: "Queso fresco", qty: "~½ lb", cost: 4.0, spansWeeks: true },
    { item: "Oaxaca cheese / quesillo", qty: "~½ lb", cost: 4.0, spansWeeks: true },
    { item: "Tomatoes", qty: "~3 lb", cost: 4.0 },
    { item: "Tomatillos", qty: "1 lb", cost: 2.0 },
    {
      item: "Dried chiles (guajillo, ancho, árbol)",
      qty: "a few of each",
      cost: 4.0,
      spansWeeks: true,
    },
    { item: "White onions", qty: "~3 lb", cost: 3.0 },
    { item: "Garlic", qty: "2 heads", cost: 2.0, spansWeeks: true },
    { item: "Serrano / jalapeño chiles", qty: "a handful", cost: 1.5 },
    { item: "Cilantro + epazote", qty: "", cost: 2.0 },
    { item: "Limes", qty: "6", cost: 2.0 },
    { item: "Crema", qty: "1 small", cost: 3.0 },
    { item: "Lard or oil", qty: "", cost: 5.0, spansWeeks: true },
  ],
  firstShopTotal: 58,
  steadyStateWeekly: 47,
};

export const week5Maiz: WeekPlan = {
  slug: "mx-week-5-maiz",
  number: 5,
  cuisine: "mexican",
  theme: "Maíz",
  title: "Week 5 — Maíz (beyond the tortilla)",
  description:
    "Corn in its other lives: nixtamalized whole into pozole, steamed in a husk as tamales, off the cob as esquites, warm in the cup as atole. The same sacred grain, a half-dozen transformations.",
  context:
    `Corn is not only the tortilla. This week explores its other lives: pozole, where nixtamalized corn is cooked whole into a great celebratory hominy stew that stretches a little pork across a huge pot; tamales, masa steamed in a husk — the original portable meal, made ahead and reheated all week; esquites and elote, corn off the cob and on; and atole, the warm corn drink. The same sacred grain, a half-dozen transformations — and the husks and cobs (cob broth!) all get used.`,
  dishes: [
    "Pozole (hominy stew, a little meat across a big pot)",
    "Esquites / elote (street corn)",
    "Tamales (masa steamed in a husk, bean- or cheese-filled)",
    "Atole (warm corn drink)",
  ],
  proteinNote: "Pozole stretches a little meat; tamales carry beans or cheese.",
  bonus: false,
  preciousThread: "A small amount of pork or chicken for the pozole pot.",
  engine: [
    "A big pot of pozole-rojo (the hominy stew that stretches a little pork all week)",
    "A double batch of tamales-de-frijol, steamed and stashed to reheat",
    "A pot of frijoles-de-la-olla (the bean bank, and the tamal filling)",
    "A jar of salsa-roja-asada (for the pozole table and everything after)",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      breakfast: "huevos-a-la-mexicana with warm tortillas",
      lunch: "esquites + a quesadilla while the pozole simmers",
      dinner: "pozole-rojo, fully garnished — the Sunday pot",
      estCalories: 2050,
      estProtein: 106,
    },
    {
      day: "Mon",
      breakfast: "tamales-de-frijol with atole",
      lunch: "leftover pozole-rojo with extra hominy and beans",
      dinner: "quesadillas-de-maiz with esquites on the side",
      estCalories: 2000,
      estProtein: 102,
    },
    {
      day: "Tue",
      breakfast: "huevos-rancheros over a tamal, split open",
      lunch: "pozole-rojo, the pot stretched with more hominy",
      dinner: "frijoles-de-la-olla with tortillas and salsa-roja-asada",
      estCalories: 2010,
      estProtein: 104,
    },
    {
      day: "Wed",
      breakfast: "tamales-de-frijol reheated on the comal + atole",
      lunch: "esquites bowl with beans and queso fresco",
      dinner: "quesadillas-de-maiz with frijoles-refritos and salsa-verde",
      estCalories: 2020,
      estProtein: 105,
    },
    {
      day: "Thu",
      breakfast: "huevos-a-la-mexicana with a warm tamal",
      lunch: "last of the pozole-rojo over rice",
      dinner: "elote — corn on the cob with crema, cheese, chile — + frijoles-de-la-olla",
      estCalories: 1990,
      estProtein: 100,
    },
    {
      day: "Fri",
      breakfast: "chilaquiles-rojos with an egg",
      lunch: "tamales-de-frijol + esquites",
      dinner: "frijoles-charros with tortillas and the last of the salsa",
      estCalories: 2030,
      estProtein: 107,
    },
    {
      day: "Sat",
      breakfast: "atole + the final tamales reheated",
      lunch: "esquites with the last ears of corn and queso fresco",
      dinner: "pozole-style soup from the cob broth + hominy + beans + every leftover — nothing wasted",
      estCalories: 2040,
      estProtein: 103,
    },
  ],
  shopping: [
    { item: "Dried/canned hominy (maíz pozolero)", qty: "~3 lb dried or 2 large cans", cost: 5.0 },
    { item: "Pork shoulder / neck bones (for the pozole pot)", qty: "~1.5 lb", cost: 6.5 },
    { item: "Masa harina (corn)", qty: "~4 lb bag", cost: 4.5 },
    { item: "Dried pinto or black beans", qty: "2 lb", cost: 2.5 },
    { item: "Corn husks (hojas para tamal)", qty: "1 bag", cost: 2.0 },
    {
      item: "Eggs",
      qty: "1½ dozen",
      cost: 6.0,
      note: "breakfasts + huevos rancheros over tamales",
    },
    { item: "Corn (ears + kernels for esquites/elote)", qty: "~8 ears / a bag", cost: 4.0 },
    {
      item: "Dried chiles (guajillo, ancho, árbol)",
      qty: "a few of each",
      cost: 4.0,
      spansWeeks: true,
    },
    { item: "Queso fresco / cotija", qty: "~½ lb", cost: 4.0, spansWeeks: true },
    { item: "White onions", qty: "~3 lb", cost: 3.0 },
    { item: "Garlic", qty: "2 heads", cost: 2.0, spansWeeks: true },
    { item: "Tomatoes + tomatillos", qty: "~2 lb", cost: 3.0 },
    { item: "Crema", qty: "1 small", cost: 3.0 },
    { item: "Limes + cilantro + epazote", qty: "", cost: 3.0 },
    { item: "Lard or oil", qty: "", cost: 5.0, spansWeeks: true },
  ],
  firstShopTotal: 60,
  steadyStateWeekly: 50,
};

export const week6Verduras: WeekPlan = {
  slug: "mx-week-6-verduras",
  number: 6,
  cuisine: "mexican",
  theme: "Verduras",
  title: "Week 6 — Verduras y la Milpa",
  description:
    "The third sister and her companions — the most direct taste of the milpa. Nopales, squash and its blossom, wild quelites, rajas with corn and cream. Eat the whole plant and the whole season.",
  context:
    `The third sister and her companions — the most direct taste of the milpa. Nopales (cactus paddles, nearly free and full of fiber), calabacita (squash) and its flor de calabaza (blossom), quelites (wild greens like verdolagas/purslane), and rajas (roasted chile strips with corn and cream). This is eating the whole plant and the whole season — in a pot of sopa de guías, even the squash vine and blossom go in, nothing of the plant wasted.`,
  dishes: [
    "Nopales (cactus paddle salad / con huevo)",
    "Calabacitas (squash, corn, cheese)",
    "Rajas con crema (roasted chile strips)",
    "Quelites / verdolagas (purslane) with beans",
  ],
  proteinNote: "Paired with beans, eggs, or a little cheese.",
  bonus: false,
  preciousThread: "Crema and queso fresco for the rajas and squash.",
  engine: [
    "A big pot of frijoles de la olla (the protein bank — vegetables won't carry it)",
    "Cleaned and griddled nopales, ready to fold into eggs or tacos all week",
    "A jar of salsa verde and a jar of salsa roja asada",
    "Roasted poblanos peeled into rajas, plus a batch of frijoles-refritos",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      breakfast: "nopales-con-huevo with warm tortillas",
      lunch: "calabacitas with corn, queso fresco, and beans on the side",
      dinner: "rajas-con-crema tacos with frijoles-de-la-olla and a fried egg",
      estCalories: 2040,
      estProtein: 106,
    },
    {
      day: "Mon",
      breakfast: "huevos-a-la-mexicana with refried beans",
      lunch: "verdolagas (purslane) stewed with frijoles-de-la-olla and tortillas",
      dinner: "quesadillas-de-maiz stuffed with calabacitas and Oaxaca cheese",
      estCalories: 2000,
      estProtein: 102,
    },
    {
      day: "Tue",
      breakfast: "nopales-con-huevo with salsa-roja-asada",
      lunch: "rajas-con-crema folded into tortillas with beans",
      dinner: "calabacitas guisadas with a fried egg and frijoles-refritos",
      estCalories: 2010,
      estProtein: 104,
    },
    {
      day: "Wed",
      breakfast: "eggs scrambled with quelites + tortilla + beans",
      lunch: "nopal-and-bean tacos with queso fresco and salsa-verde",
      dinner: "calabacitas with corn and cheese, frijoles-de-la-olla on the side",
      estCalories: 2020,
      estProtein: 103,
    },
    {
      day: "Thu",
      breakfast: "huevos-a-la-mexicana with refried beans and tortilla",
      lunch: "molletes — refried beans and cheese broiled, with a nopal salad",
      dinner: "rajas con crema and elote folded into quesadillas-de-maiz",
      estCalories: 2030,
      estProtein: 105,
    },
    {
      day: "Fri",
      breakfast: "nopales-con-huevo with salsa-verde and beans",
      lunch: "verdolagas with frijoles-refritos and warm tortillas",
      dinner: "calabacitas con queso, a fried egg, and frijoles-de-la-olla",
      estCalories: 2000,
      estProtein: 102,
    },
    {
      day: "Sat",
      breakfast: "huevos-rancheros over the last refried beans",
      lunch: "nopal-and-quelite tacos with queso fresco and salsa",
      dinner: "sopa de guías — squash vine, blossom, calabacita, and corn in one pot, finished with beans and queso; the whole plant goes in, nothing wasted",
      estCalories: 2050,
      estProtein: 105,
    },
  ],
  shopping: [
    { item: "Nopales (cactus paddles)", qty: "~3 lb / 6 paddles", cost: 3.0 },
    { item: "Calabacita (Mexican squash / zucchini)", qty: "~4 lb", cost: 4.0 },
    {
      item: "Squash vine + flor de calabaza (for sopa de guías)",
      qty: "1 bunch",
      cost: 2.5,
      note: "the zero-waste finale — the whole plant",
    },
    { item: "Verdolagas / quelites (purslane, wild greens)", qty: "2 bunches", cost: 2.5 },
    { item: "Poblano chiles (for rajas)", qty: "~2 lb", cost: 3.5 },
    { item: "Corn (for calabacitas / elote)", qty: "5 ears", cost: 2.5 },
    {
      item: "Eggs",
      qty: "2 dozen",
      cost: 8.0,
      note: "protein backbone — vegetables can't carry it alone",
    },
    { item: "Dried pinto or black beans", qty: "2 lb", cost: 2.5 },
    { item: "Queso fresco", qty: "~¾ lb", cost: 5.0, spansWeeks: true },
    { item: "Crema", qty: "1 medium", cost: 3.5, spansWeeks: true },
    { item: "Oaxaca cheese / quesillo", qty: "~½ lb", cost: 4.0, spansWeeks: true },
    { item: "Tomatoes + tomatillos", qty: "~3 lb total", cost: 4.0 },
    { item: "White onions", qty: "~3 lb", cost: 3.0 },
    { item: "Garlic", qty: "2 heads", cost: 2.0, spansWeeks: true },
    { item: "Dried chiles (guajillo, árbol) + epazote", qty: "a few + 1 bunch", cost: 3.0, spansWeeks: true },
    { item: "Limes + cilantro", qty: "6 + 1 bunch", cost: 2.5 },
    { item: "Lard or oil", qty: "", cost: 4.0, spansWeeks: true },
  ],
  firstShopTotal: 56,
  steadyStateWeekly: 47,
};

export const week7Guisos: WeekPlan = {
  slug: "mx-week-7-guisos",
  number: 7,
  cuisine: "mexican",
  theme: "Guisos",
  title: "Week 7 — Guisos (the Sunday pot)",
  description:
    "The celebratory but still-frugal finale — how the poor ate like kings on Sundays by stretching a little meat through a big pot, ladled over rice or scooped with tortillas. The communal table, the reward at the end of the arc.",
  context:
    `The celebratory but still-frugal finale — how the poor ate like kings on Sundays by stretching a little meat through a big pot. Tinga (shredded chicken in a smoky chipotle-tomato sauce), picadillo (a little ground meat bulked with potato, carrot, and raisins), frijoles puercos, and mole in its everyday form. One affordable protein feeds many, ladled over rice or scooped with tortillas — the communal table, and the reward at the end of the arc. Leftovers become tomorrow's taco and torta fillings.`,
  dishes: [
    "Tinga de pollo (chicken in smoky chipotle-tomato)",
    "Picadillo (a little meat bulked with potato, carrot, raisins)",
    "Mole in its everyday form",
    "Frijoles puercos",
  ],
  proteinNote: "Meat as a flavor-carrier over the bean-and-corn base.",
  bonus: false,
  preciousThread: "The week's one cut of meat (+ Mexican chocolate for a mole).",
  engine: [
    "The big Sunday guiso: tinga-de-pollo — one bird poached, shredded, simmered in chipotle-tomato (the week's headline pot)",
    "A pot of picadillo — a little ground meat stretched with potato, carrot, and raisins",
    "A big pot of frijoles de la olla, half turned into frijoles-puercos",
    "A double batch of masa → a stack of fresh tortillas (and chips from the rest)",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      breakfast: "huevos-a-la-mexicana",
      lunch: "esquites + a quesadilla while the pots come together",
      dinner: "tinga-de-pollo tostadas with crema, queso fresco, and frijoles-refritos — the Sunday feast",
      estCalories: 2050,
      estProtein: 106,
    },
    {
      day: "Mon",
      breakfast: "chilaquiles-rojos with an egg",
      lunch: "tinga-de-pollo tacos with salsa-verde",
      dinner: "picadillo over rice with warm tortillas and frijoles-de-la-olla",
      estCalories: 2030,
      estProtein: 105,
    },
    {
      day: "Tue",
      breakfast: "huevos-rancheros",
      lunch: "picadillo tacos with salsa-roja-asada",
      dinner: "frijoles-puercos with tortillas and a fried egg",
      estCalories: 2010,
      estProtein: 104,
    },
    {
      day: "Wed",
      breakfast: "eggs + tortilla + salsa",
      lunch: "tinga-de-pollo quesadillas-de-maiz",
      dinner: "everyday mole over the last of the chicken, with rice and tortillas",
      estCalories: 2040,
      estProtein: 103,
    },
    {
      day: "Thu",
      breakfast: "chilaquiles-rojos with shredded tinga on top",
      lunch: "frijoles-puercos molletes, broiled with cheese",
      dinner: "picadillo-stuffed chiles with salsa-roja-asada and beans",
      estCalories: 2000,
      estProtein: 102,
    },
    {
      day: "Fri",
      breakfast: "huevos-a-la-mexicana",
      lunch: "tinga-de-pollo tortas — chicken piled on a roll with beans and crema",
      dinner: "quesadillas-de-maiz with frijoles-refritos and salsa-verde",
      estCalories: 2020,
      estProtein: 104,
    },
    {
      day: "Sat",
      breakfast: "huevos-rancheros",
      lunch: "esquites + a quesadilla",
      dinner: "the finale plate — every leftover guiso (tinga + picadillo + puercos) folded into tacos and tortas, nothing wasted",
      estCalories: 2050,
      estProtein: 107,
    },
  ],
  shopping: [
    { item: "Whole chicken (for tinga)", qty: "~3½ lb bird", cost: 8.0, note: "one bird stretched all week" },
    { item: "Ground pork or beef (for picadillo)", qty: "~¾ lb", cost: 4.5, note: "bulked with potato + carrot" },
    { item: "Bacon / chorizo ends (for frijoles-puercos)", qty: "~¼ lb", cost: 2.5 },
    { item: "Masa harina (corn)", qty: "~4 lb bag", cost: 4.5 },
    { item: "Dried pinto or black beans", qty: "2 lb", cost: 2.5 },
    { item: "Eggs", qty: "2 dozen", cost: 8.0, note: "stacks protein on the lighter days" },
    { item: "Chipotles in adobo", qty: "1 can", cost: 2.5, spansWeeks: true },
    { item: "Mexican chocolate", qty: "1 tablet", cost: 3.0, spansWeeks: true, note: "for the everyday mole" },
    { item: "Tomatoes", qty: "~3 lb", cost: 4.0 },
    { item: "Tomatillos", qty: "1 lb", cost: 2.0 },
    { item: "Queso fresco", qty: "~½ lb", cost: 4.0, spansWeeks: true },
    { item: "Potatoes + carrots", qty: "~2 lb / 3 carrots", cost: 3.0 },
    { item: "Raisins", qty: "small bag", cost: 1.5 },
    { item: "Rice", qty: "2 lb", cost: 2.0 },
    { item: "White onions", qty: "~3 lb", cost: 3.0 },
    { item: "Garlic", qty: "2 heads", cost: 2.0, spansWeeks: true },
    { item: "Cilantro + limes", qty: "1 bunch / 6", cost: 2.5 },
    { item: "Crema", qty: "1 small", cost: 3.0 },
    { item: "Lard or oil", qty: "", cost: 5.0, spansWeeks: true },
  ],
  firstShopTotal: 62,
  steadyStateWeekly: 52,
};

export const mexicanWeeks: WeekPlan[] = [
  mxWeek1Masa,
  week2Frijoles,
  week3Chiles,
  week4Huevos,
  week5Maiz,
  week6Verduras,
  week7Guisos,
];
