import type { WeekPlan } from "../types";

// Challenge #4 — North India: the everyday thali.
// The full seven-week arc, every week built out into an executable WeekPlan
// (engine + 7 days + costed shopping list). cuisine is "north-indian"; the
// engine is cuisine-agnostic, so these slot into the shared content arrays,
// tagged by cuisine. These are the curated, pregenerated defaults — the AI menu
// generator lets users compose variations on top of the same recipe pool.
//
// The FOUNDATION — dal/rice/roti, ghee, and the onion-tomato-ginger-garlic
// masala base — is the constant beneath every week; it lives in each week's
// engine, never as a theme. Each theme is a real dinner category you actually
// eat. Dinner slugs reference recipes in src/content/recipes/* where they exist,
// otherwise short free text.

export const niWeek1Dal: WeekPlan = {
  slug: "ni-week-1-dal",
  number: 1,
  cuisine: "north-indian",
  theme: "Dal",
  title: "Week 1 — Dal",
  description:
    "Start where the North Indian kitchen actually starts: a pot of dal, a stack of roti, a bowl of rice. The simplest dinner on the arc and the one eaten most nights of the year — a different lentil each day, each finished with its own sizzling tadka.",
  context:
    `The everyday North Indian dinner is dal-roti — a pot of split lentils, hot rotis off the tawa, and a spoon of rice — and it is what most families eat most nights. The thali logic is balance on one plate: dal for protein, roti and rice for the staple, a sliver of pickle and onion for the sharp note. What turns plain boiled lentils into dal is the tadka — whole cumin, garlic, and dried chile bloomed in hot ghee and poured over the pot at the end. This is vegetarian by default, not by restriction; the legume carries the protein and the ghee carries the flavor. Master the dal and the tadka this week and the rest of the arc is variation.`,
  dishes: [
    "Dal tadka (yellow lentils with a cumin-garlic tadka)",
    "Moong dal (the lightest, quickest dal)",
    "Masoor dal (red lentils, melts in fifteen minutes)",
    "Chana dal (split chickpeas, nutty and substantial)",
  ],
  proteinNote:
    "Split lentils carry ~16–18g protein per cooked cup; a bowl of dal with roti and rice clears most of the day's floor with no meat.",
  bonus: false,
  preciousThread: "A jar of homemade ghee to finish every dal.",
  engine: [
    "ghee — render a jar; the tadka and every roti rest on it (the constant foundation)",
    "onion-tomato-masala — a base of onion, tomato, ginger, and garlic cooked down, the foundation under every pot",
    "dal-tadka — a big base pot of yellow dal, retadka'd fresh each night",
    "roti — a rest batch of atta dough, rolled and griddled to order; rice cooked alongside",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "dal-tadka with roti and rice — the headline pot",
      estCalories: 640,
      estProtein: 22,
    },
    {
      day: "Mon",
      dinner: "moong-dal with roti and a side of rice",
      estCalories: 600,
      estProtein: 20,
    },
    {
      day: "Tue",
      dinner: "masoor-dal with jeera rice",
      estCalories: 620,
      estProtein: 21,
    },
    {
      day: "Wed",
      dinner: "chana-dal with roti — the nutty, substantial dal",
      estCalories: 680,
      estProtein: 24,
    },
    {
      day: "Thu",
      dinner: "dal-tadka, the pot deepened, with roti and rice",
      estCalories: 650,
      estProtein: 22,
    },
    {
      day: "Fri",
      dinner: "moong-masoor mixed dal with roti",
      estCalories: 630,
      estProtein: 23,
    },
    {
      day: "Sat",
      dinner: "the week's dals pooled with a fresh tadka over rice — nothing wasted",
      estCalories: 660,
      estProtein: 24,
    },
  ],
  shopping: [
    { item: "Toor / arhar dal (split pigeon peas)", qty: "2 lb", cost: 3.0, note: "the bank — the everyday dal" },
    { item: "Moong dal (split mung)", qty: "1 lb", cost: 1.6 },
    { item: "Masoor dal (split red lentils)", qty: "1 lb", cost: 1.5 },
    { item: "Chana dal (split chickpeas)", qty: "1 lb", cost: 1.6 },
    { item: "Atta (whole wheat flour, for roti)", qty: "5 lb", cost: 4.0, note: "rolls into roti all week" },
    { item: "Basmati rice", qty: "2 lb", cost: 3.0 },
    { item: "Ghee (or butter to clarify)", qty: "1 lb", cost: 5.0, spansWeeks: true, note: "the precious thread — finishes every dal" },
    { item: "Onions", qty: "~4 lb", cost: 3.0 },
    { item: "Tomatoes", qty: "~2 lb", cost: 2.5 },
    { item: "Ginger + garlic", qty: "1 hand / 2 heads", cost: 2.5, spansWeeks: true },
    { item: "Green chiles + cilantro", qty: "a handful / 1 bunch", cost: 1.5 },
    { item: "Cumin, turmeric, dried red chiles, coriander", qty: "a starter set", cost: 5.0, spansWeeks: true, note: "the spice box that powers the arc" },
    { item: "Salt + cooking oil", qty: "", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 27,
  steadyStateWeekly: 15,
};

export const niWeek2RajmaChole: WeekPlan = {
  slug: "ni-week-2-rajma-chole",
  number: 2,
  cuisine: "north-indian",
  theme: "Rajma & Chole",
  title: "Week 2 — Rajma & Chole",
  description:
    "The Sunday-favorite beans. Kidney beans simmered to a thick gravy over rice (rajma-chawal) and chickpeas in a dark, tangy masala (chole) — the heartier cousins of dal, slow-cooked from a soaked pot and eaten with rice or bhatura.",
  context:
    `When dal-roti is the everyday, rajma-chawal is the beloved Sunday — kidney beans simmered low into a thick, glossy gravy and ladled over rice, the one dish North Indian kids ask for by name. Chole is its chickpea twin: a darker, tangier masala sharpened with amchur and a pinch of chai-spiced chana masala. Both rest on the same onion-tomato-ginger-garlic foundation as the dal, only cooked longer and deeper. A pot of soaked beans costs almost nothing and gives a fuller, meatier protein than the quick lentils. Leftover rajma mashed into the next pot only makes it better.`,
  dishes: [
    "Rajma (kidney beans, the Sunday gravy)",
    "Chole (chickpeas in a dark, tangy masala)",
    "Kala chana (black chickpeas, earthy and firm)",
    "Rajma-chawal — beans over rice, the comfort plate",
  ],
  proteinNote: "Kidney beans and chickpeas bring ~15g protein per cooked cup and a meatier bite than lentils; rajma over rice clears the floor easily.",
  bonus: false,
  preciousThread: "A spoon of homemade chole masala (the dark roasted spice blend).",
  engine: [
    "onion-tomato-masala — the deep base for both rajma and chole (the constant foundation)",
    "ghee — for the tadka and to finish the gravies",
    "A big pot of soaked, slow-cooked kidney beans, split across the week",
    "roti — a rest batch of atta dough; rice and bhatura cooked alongside",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "rajma-chawal — kidney beans over rice, the headline",
      estCalories: 690,
      estProtein: 22,
    },
    {
      day: "Mon",
      dinner: "chole with roti — the dark, tangy chickpeas",
      estCalories: 680,
      estProtein: 23,
    },
    {
      day: "Tue",
      dinner: "rajma deepened on day three, with rice",
      estCalories: 700,
      estProtein: 22,
    },
    {
      day: "Wed",
      dinner: "kala-chana — earthy black chickpeas with roti",
      estCalories: 670,
      estProtein: 24,
    },
    {
      day: "Thu",
      dinner: "chole with a side of jeera rice",
      estCalories: 690,
      estProtein: 23,
    },
    {
      day: "Fri",
      dinner: "dal-tadka for a lighter night, with roti",
      estCalories: 620,
      estProtein: 21,
    },
    {
      day: "Sat",
      dinner: "rajma and chole side by side over rice — the week's beans pooled, nothing wasted",
      estCalories: 710,
      estProtein: 25,
    },
  ],
  shopping: [
    { item: "Rajma (red kidney beans, dried)", qty: "2 lb", cost: 3.6, note: "the bank for the week" },
    { item: "Chickpeas (kabuli chana, dried)", qty: "1.5 lb", cost: 2.4 },
    { item: "Kala chana (black chickpeas)", qty: "1 lb", cost: 1.8 },
    { item: "Toor dal (for the lighter night)", qty: "1 lb", cost: 1.5 },
    { item: "Atta (whole wheat flour)", qty: "3 lb", cost: 2.5 },
    { item: "Basmati rice", qty: "2 lb", cost: 3.0 },
    { item: "Onions", qty: "~5 lb", cost: 3.5, note: "the long deep base eats onions" },
    { item: "Tomatoes", qty: "~3 lb", cost: 3.5 },
    { item: "Ginger + garlic", qty: "1 hand / 2 heads", cost: 2.5, spansWeeks: true },
    { item: "Green chiles + cilantro", qty: "a handful / 1 bunch", cost: 1.5 },
    { item: "Amchur + chole/chana masala", qty: "small", cost: 3.0, spansWeeks: true, note: "the precious thread — the dark roasted blend" },
    { item: "Ghee (top up)", qty: "1/2 lb", cost: 2.5, spansWeeks: true },
    { item: "Spice box (top up: cumin, coriander, garam masala)", qty: "", cost: 2.5, spansWeeks: true },
    { item: "Oil + salt", qty: "", cost: 2.0, spansWeeks: true },
  ],
  firstShopTotal: 26,
  steadyStateWeekly: 16,
};

export const niWeek3Sabzi: WeekPlan = {
  slug: "ni-week-3-sabzi",
  number: 3,
  cuisine: "north-indian",
  theme: "Sabzi",
  title: "Week 3 — Sabzi (dry vegetable dishes)",
  description:
    "The dry vegetable side that completes the thali. Potatoes and cauliflower, okra, cumin-spiked potatoes, smoky roasted eggplant — quick-cooked vegetables tossed in the masala base, eaten with roti alongside the day's dal.",
  context:
    `A thali is never just dal and rice — there is always a sabzi, the dry or semi-dry vegetable dish that brings color, texture, and the season to the plate. Aloo-gobi (potato and cauliflower), bhindi masala (okra), jeera aloo (cumin potatoes), baingan bharta (eggplant fire-roasted and mashed) — each is a few cheap vegetables turned bright in the same onion-tomato-ginger-garlic base. The sabzi rides with the constant dal-roti foundation; it doesn't replace it. This is how the home kitchen eats the market's cheapest vegetables and makes each one taste like its own dinner. The protein still comes from the dal alongside; the sabzi is the flavor and the freshness.`,
  dishes: [
    "Aloo-gobi (potato + cauliflower)",
    "Bhindi masala (okra)",
    "Jeera aloo (cumin potatoes)",
    "Baingan bharta (smoky mashed eggplant)",
  ],
  proteinNote: "The sabzi is light on protein; the day still leans on the dal alongside it to clear the floor — sabzi-dal-roti is the full plate.",
  bonus: false,
  preciousThread: "A whole eggplant fire-roasted over the flame for the bharta's smoke.",
  engine: [
    "onion-tomato-masala — the base every sabzi is tossed into (the constant foundation)",
    "dal-tadka — a base pot of dal to pair with each sabzi for the protein",
    "ghee — for the tadka and to finish the rotis",
    "roti — a rest batch of atta dough; rice cooked alongside",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "aloo-gobi with dal and roti — the headline sabzi",
      estCalories: 620,
      estProtein: 18,
    },
    {
      day: "Mon",
      dinner: "bhindi-masala with dal and roti",
      estCalories: 600,
      estProtein: 17,
    },
    {
      day: "Tue",
      dinner: "jeera-aloo with masoor-dal and roti",
      estCalories: 640,
      estProtein: 19,
    },
    {
      day: "Wed",
      dinner: "baingan-bharta with roti — the smoky mashed eggplant",
      estCalories: 610,
      estProtein: 16,
    },
    {
      day: "Thu",
      dinner: "aloo-gobi deepened, with dal and rice",
      estCalories: 630,
      estProtein: 18,
    },
    {
      day: "Fri",
      dinner: "jeera-aloo with chana-dal and roti",
      estCalories: 670,
      estProtein: 22,
    },
    {
      day: "Sat",
      dinner: "a mixed-sabzi plate — the week's vegetables with dal over rice, nothing wasted",
      estCalories: 650,
      estProtein: 20,
    },
  ],
  shopping: [
    { item: "Potatoes", qty: "~4 lb", cost: 3.0, note: "the bank — aloo in half the dishes" },
    { item: "Cauliflower (gobi)", qty: "1 head", cost: 2.5 },
    { item: "Okra (bhindi)", qty: "1 lb", cost: 2.5 },
    { item: "Eggplant (baingan)", qty: "~2 lb", cost: 2.5, note: "the precious thread — fire-roasted for bharta" },
    { item: "Toor + masoor + chana dal (for the protein side)", qty: "1.5 lb total", cost: 2.4 },
    { item: "Atta (whole wheat flour)", qty: "3 lb", cost: 2.5 },
    { item: "Basmati rice", qty: "1 lb", cost: 1.5 },
    { item: "Onions", qty: "~3 lb", cost: 2.5 },
    { item: "Tomatoes", qty: "~2 lb", cost: 2.5 },
    { item: "Ginger + garlic", qty: "1 hand / 2 heads", cost: 2.5, spansWeeks: true },
    { item: "Green chiles + cilantro", qty: "a handful / 1 bunch", cost: 1.5 },
    { item: "Spice box (top up: cumin, turmeric, garam masala)", qty: "", cost: 2.0, spansWeeks: true },
    { item: "Ghee (top up)", qty: "1/2 lb", cost: 2.5, spansWeeks: true },
    { item: "Oil + salt", qty: "", cost: 2.0, spansWeeks: true },
  ],
  firstShopTotal: 24,
  steadyStateWeekly: 15,
};

export const niWeek4Saag: WeekPlan = {
  slug: "ni-week-4-saag",
  number: 4,
  cuisine: "north-indian",
  theme: "Saag",
  title: "Week 4 — Saag (cooked greens)",
  description:
    "The Punjabi winter table. Mustard greens slow-cooked to a velvety sarson ka saag (with makki di roti), spinach stewed into palak, and potato-with-fenugreek aloo methi — leafy greens simmered soft and finished with ghee.",
  context:
    `Saag is the green heart of the Punjabi winter — mustard greens (sarson ka saag) simmered for hours until velvety, mashed smooth, and finished with a knob of ghee, eaten with makki di roti (corn flatbread) and a smear of white butter. Palak (spinach) and aloo methi (potato with fresh fenugreek) carry the same idea on weeknights. The greens are cheapest and sweetest after the first frost, which is exactly when this dish belongs. It rests on the same masala foundation and the same ghee finish as every week; the dal-roti base is still there underneath. A few greens, slow time, and ghee turn winter's cheapest leaves into the season's richest plate.`,
  dishes: [
    "Sarson ka saag (mustard greens + makki di roti)",
    "Palak (stewed spinach)",
    "Aloo methi (potato + fresh fenugreek)",
    "Saag with a knob of white butter",
  ],
  proteinNote: "Greens add little protein; the dal alongside and a paneer cube or two in the palak carry the floor — saag-dal-roti is the full plate.",
  bonus: false,
  preciousThread: "A spoon of white butter (makkhan) melting over the hot saag.",
  engine: [
    "onion-tomato-masala — the base under the saag and the dal (the constant foundation)",
    "ghee + white butter — the fat that finishes the greens (the constant foundation)",
    "A big pot of slow-cooked, mashed mustard greens, ready to reheat all week",
    "dal-tadka and roti — the base pot and atta dough; makki flour for makki di roti",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "sarson-ka-saag with makki di roti — the headline",
      estCalories: 660,
      estProtein: 18,
    },
    {
      day: "Mon",
      dinner: "palak with roti and a side of dal",
      estCalories: 630,
      estProtein: 19,
    },
    {
      day: "Tue",
      dinner: "aloo-methi with masoor-dal and roti",
      estCalories: 650,
      estProtein: 20,
    },
    {
      day: "Wed",
      dinner: "sarson-ka-saag again, deepened, with makki di roti",
      estCalories: 670,
      estProtein: 18,
    },
    {
      day: "Thu",
      dinner: "palak with a few paneer cubes and roti",
      estCalories: 680,
      estProtein: 23,
    },
    {
      day: "Fri",
      dinner: "aloo-methi with chana-dal and roti",
      estCalories: 660,
      estProtein: 22,
    },
    {
      day: "Sat",
      dinner: "the week's saag pooled with dal over rice, a knob of butter on top — nothing wasted",
      estCalories: 670,
      estProtein: 20,
    },
  ],
  shopping: [
    { item: "Mustard greens (sarson)", qty: "3 bunches", cost: 4.5, note: "the bank — the slow winter saag" },
    { item: "Spinach (palak)", qty: "2 bunches", cost: 3.0 },
    { item: "Fresh fenugreek (methi)", qty: "1 bunch", cost: 2.0 },
    { item: "Makki ka atta (corn flour, for makki di roti)", qty: "2 lb", cost: 2.0 },
    { item: "Potatoes (for aloo methi)", qty: "~2 lb", cost: 1.5 },
    { item: "Paneer (a small block for the palak)", qty: "~1/2 lb", cost: 3.0 },
    { item: "Toor + masoor + chana dal", qty: "1.5 lb total", cost: 2.4 },
    { item: "Atta (whole wheat flour)", qty: "2 lb", cost: 1.5 },
    { item: "Basmati rice", qty: "1 lb", cost: 1.5 },
    { item: "Onions + tomatoes", qty: "~3 lb / ~2 lb", cost: 5.0 },
    { item: "Ginger + garlic", qty: "1 hand / 2 heads", cost: 2.5, spansWeeks: true },
    { item: "White butter / ghee", qty: "1/2 lb", cost: 3.0, spansWeeks: true, note: "the precious thread — melts over the saag" },
    { item: "Spice box (top up)", qty: "", cost: 2.0, spansWeeks: true },
    { item: "Oil + salt", qty: "", cost: 2.0, spansWeeks: true },
  ],
  firstShopTotal: 27,
  steadyStateWeekly: 17,
};

export const niWeek5Kadhi: WeekPlan = {
  slug: "ni-week-5-kadhi",
  number: 5,
  cuisine: "north-indian",
  theme: "Kadhi & Pakora",
  title: "Week 5 — Kadhi & Pakora",
  description:
    "The tangy yogurt-and-gram-flour curry. Sour yogurt thickened with besan, simmered low, studded with soft pakora dumplings — kadhi-pakora over rice — with crisp mixed-vegetable pakoras and a cooling boondi raita on the side.",
  context:
    `Kadhi is the kitchen's thrift made delicious: slightly sour yogurt whisked with besan (gram flour) and simmered slow into a glossy golden curry, then finished with a tempered tadka of cumin and dried chile. Drop soft besan pakoras into it and you have kadhi-pakora, ladled over rice — a whole dinner from yogurt, flour, and an onion. Crisp mixed-vegetable pakoras fried fresh and a cooling boondi raita round out the meal. The besan and yogurt do the protein work the dal usually does, so the constant foundation flexes here — the base masala and ghee tadka stay, the legume becomes gram flour. It's the dish that turns yesterday's slightly-too-sour yogurt into the best plate of the week.`,
  dishes: [
    "Kadhi-pakora (yogurt-besan curry with dumplings)",
    "Mixed-veg pakora (crisp fritters)",
    "Boondi raita (cooling yogurt side)",
    "Kadhi-chawal — kadhi over rice",
  ],
  proteinNote: "Besan and yogurt carry the protein the dal usually does — kadhi over rice with raita clears the floor without a separate dal.",
  bonus: false,
  preciousThread: "A bowl of thick set yogurt (dahi), soured just right for the kadhi.",
  engine: [
    "onion-tomato-masala + ghee tadka — the constant base and the cumin-chile tadka over the kadhi",
    "A big pot of slow-simmered kadhi base (yogurt + besan), reheated all week",
    "A batch of besan pakora batter, fried to order for the kadhi and the plate",
    "roti and rice — atta dough and basmati alongside (the constant foundation)",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "kadhi-pakora over rice — the headline",
      estCalories: 640,
      estProtein: 18,
    },
    {
      day: "Mon",
      dinner: "kadhi-pakora with rice (kadhi-chawal) and a side of mixed-veg-pakora",
      estCalories: 650,
      estProtein: 17,
    },
    {
      day: "Tue",
      dinner: "dal-tadka with roti for a lighter night",
      estCalories: 620,
      estProtein: 21,
    },
    {
      day: "Wed",
      dinner: "kadhi-pakora again, deepened, over rice with boondi-raita",
      estCalories: 660,
      estProtein: 18,
    },
    {
      day: "Thu",
      dinner: "mixed-veg-pakora with roti and dal",
      estCalories: 670,
      estProtein: 19,
    },
    {
      day: "Fri",
      dinner: "kadhi-pakora with rice (kadhi-chawal) and a green-chile tadka",
      estCalories: 640,
      estProtein: 17,
    },
    {
      day: "Sat",
      dinner: "the week's kadhi reheated with fresh pakoras dropped in, over rice — nothing wasted",
      estCalories: 660,
      estProtein: 19,
    },
  ],
  shopping: [
    { item: "Besan (gram flour)", qty: "2 lb", cost: 3.0, note: "the bank — kadhi and pakora both" },
    { item: "Yogurt / dahi (or milk to set)", qty: "~2 qt", cost: 4.0, note: "the precious thread — soured for the kadhi" },
    { item: "Mixed vegetables (onion, potato, spinach for pakora)", qty: "~3 lb", cost: 3.0 },
    { item: "Toor + masoor dal (for the lighter nights)", qty: "1 lb total", cost: 1.6 },
    { item: "Atta (whole wheat flour)", qty: "2 lb", cost: 1.5 },
    { item: "Basmati rice", qty: "2 lb", cost: 3.0, note: "kadhi rides on rice" },
    { item: "Boondi (or extra besan to fry)", qty: "small", cost: 1.5 },
    { item: "Onions + tomatoes", qty: "~3 lb / ~1 lb", cost: 3.5 },
    { item: "Ginger + garlic", qty: "1 hand / 2 heads", cost: 2.5, spansWeeks: true },
    { item: "Green chiles + cilantro", qty: "a handful / 1 bunch", cost: 1.5 },
    { item: "Spice box (top up: cumin, turmeric, fenugreek)", qty: "", cost: 2.0, spansWeeks: true },
    { item: "Ghee (top up)", qty: "1/2 lb", cost: 2.5, spansWeeks: true },
    { item: "Frying oil + salt", qty: "", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 26,
  steadyStateWeekly: 16,
};

export const niWeek6Khichdi: WeekPlan = {
  slug: "ni-week-6-khichdi",
  number: 6,
  cuisine: "north-indian",
  theme: "Khichdi & Pulao",
  title: "Week 6 — Khichdi & Pulao",
  description:
    "The one-pot rice meals. Rice and lentils cooked soft together into comforting khichdi, vegetables folded into a fragrant veg pulao, and the spiced rice-and-lentil tahari — the nights when the whole dinner comes out of a single pot.",
  context:
    `Khichdi is the original Indian comfort food and the one-pot answer to a tired evening: rice and moong dal cooked soft together with turmeric and a ghee tadka, the dish given to babies and the unwell and craved by everyone else. Veg pulao folds the season's vegetables and whole spices into fragrant basmati; tahari is its lentil-and-potato cousin from the North Indian Muslim kitchen. These are the nights the constant dal-rice foundation becomes the whole dinner in a single pot — the lentil and the rice no longer side by side but cooked into one. A spoon of ghee and a bowl of yogurt or papad turn the plainest khichdi into a full, balanced plate.`,
  dishes: [
    "Khichdi (rice + moong dal, the comfort one-pot)",
    "Veg pulao (fragrant basmati with vegetables)",
    "Tahari (spiced rice with lentils + potato)",
    "Khichdi with ghee, yogurt, and papad",
  ],
  proteinNote: "Moong dal cooked into the rice carries the protein; khichdi with a bowl of yogurt clears the floor in a single pot.",
  bonus: false,
  preciousThread: "A generous spoon of ghee melting into the hot khichdi.",
  engine: [
    "ghee + the cumin tadka — the constant fat and tadka poured over every one-pot",
    "onion-tomato-masala — the base for the pulao and tahari (the constant foundation)",
    "A pot of khichdi (rice + moong dal), reheated and loosened all week",
    "Soaked basmati and prepped vegetables for the pulao and tahari; roti dough on standby",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "khichdi with ghee, yogurt, and papad — the headline one-pot",
      estCalories: 620,
      estProtein: 18,
    },
    {
      day: "Mon",
      dinner: "veg-pulao with a side of raita",
      estCalories: 650,
      estProtein: 16,
    },
    {
      day: "Tue",
      dinner: "tahari — spiced rice with lentils and potato",
      estCalories: 660,
      estProtein: 19,
    },
    {
      day: "Wed",
      dinner: "khichdi again, with a cumin-ghee tadka and pickle",
      estCalories: 630,
      estProtein: 18,
    },
    {
      day: "Thu",
      dinner: "veg-pulao with dal-tadka on the side",
      estCalories: 680,
      estProtein: 22,
    },
    {
      day: "Fri",
      dinner: "tahari with a bowl of yogurt",
      estCalories: 650,
      estProtein: 19,
    },
    {
      day: "Sat",
      dinner: "the week's rice and dal pooled into one last khichdi, ghee on top — nothing wasted",
      estCalories: 640,
      estProtein: 19,
    },
  ],
  shopping: [
    { item: "Basmati rice", qty: "4 lb", cost: 6.0, note: "the bank — every one-pot rides on rice" },
    { item: "Moong dal (for khichdi)", qty: "2 lb", cost: 3.2 },
    { item: "Toor dal (for the side dal + tahari)", qty: "1 lb", cost: 1.5 },
    { item: "Mixed vegetables (peas, carrot, beans, potato)", qty: "~3 lb", cost: 3.5 },
    { item: "Yogurt / dahi (for raita)", qty: "~1 qt", cost: 2.0 },
    { item: "Papad", qty: "1 pack", cost: 1.5 },
    { item: "Atta (whole wheat flour)", qty: "2 lb", cost: 1.5 },
    { item: "Onions + tomatoes", qty: "~3 lb / ~1 lb", cost: 3.5 },
    { item: "Ginger + garlic", qty: "1 hand / 2 heads", cost: 2.5, spansWeeks: true },
    { item: "Whole spices (bay, clove, cardamom, cinnamon for pulao)", qty: "small", cost: 2.5, spansWeeks: true },
    { item: "Green chiles + cilantro", qty: "a handful / 1 bunch", cost: 1.5 },
    { item: "Ghee (top up — khichdi wants it)", qty: "1/2 lb", cost: 3.0, spansWeeks: true, note: "the precious thread" },
    { item: "Spice box (top up) + oil + salt", qty: "", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 25,
  steadyStateWeekly: 15,
};

export const niWeek7Paneer: WeekPlan = {
  slug: "ni-week-7-paneer",
  number: 7,
  cuisine: "north-indian",
  theme: "Paneer (the feast)",
  title: "Week 7 — Paneer (the feast)",
  description:
    "The affordable luxury that closes the arc. Fresh cheese curdled at home from a pot of milk, simmered into matar paneer, palak paneer, scrambled paneer bhurji, and the rich shahi paneer — the dish that makes a weeknight feel like a celebration.",
  context:
    `Paneer is the North Indian feast made affordable: fresh cheese curdled at home from milk and lemon, costing a fraction of meat yet rich enough to crown a celebration plate. Matar paneer (with peas), palak paneer (in spinach), paneer bhurji (scrambled with onion and tomato), and the cream-rich shahi paneer are the dishes saved for guests and Sundays. They rest on the same onion-tomato-ginger-garlic foundation and the same ghee finish as the everyday dal — only here the legume gives way to the cheese. This is the week the arc consolidates: the constant dal-roti base is still underneath, and the paneer is the one mound of luxury added on top, proving that the everyday plate and the feast plate are the same plate. The leftover whey and trimmings go into the dough and the dal — nothing wasted, even at the feast.`,
  dishes: [
    "Matar paneer (paneer + peas)",
    "Palak paneer (paneer in spinach)",
    "Paneer bhurji (scrambled paneer)",
    "Shahi paneer (the rich, creamy feast)",
  ],
  proteinNote: "Paneer brings ~14g protein per 100g and pairs with the dal underneath; matar paneer with roti clears the floor comfortably.",
  bonus: false,
  preciousThread: "A gallon of whole milk curdled at home into a fresh block of paneer.",
  engine: [
    "Fresh paneer — curdle a big block from milk and lemon, pressed and cubed for the week (the feast's affordable luxury)",
    "onion-tomato-masala — the rich base under every paneer gravy (the constant foundation)",
    "ghee + a little cream — the fat that makes the gravies feast-rich",
    "dal-tadka and roti — the base pot and atta dough still underneath (the constant foundation)",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "matar-paneer with roti — the headline feast",
      estCalories: 700,
      estProtein: 24,
    },
    {
      day: "Mon",
      dinner: "palak-paneer with roti and rice",
      estCalories: 690,
      estProtein: 25,
    },
    {
      day: "Tue",
      dinner: "paneer-bhurji with roti — scrambled and quick",
      estCalories: 670,
      estProtein: 23,
    },
    {
      day: "Wed",
      dinner: "shahi-paneer with rice — the rich, creamy one",
      estCalories: 720,
      estProtein: 24,
    },
    {
      day: "Thu",
      dinner: "matar-paneer deepened, with dal and roti",
      estCalories: 700,
      estProtein: 26,
    },
    {
      day: "Fri",
      dinner: "palak-paneer with jeera rice",
      estCalories: 690,
      estProtein: 25,
    },
    {
      day: "Sat",
      dinner: "the week's paneer trimmings scrambled into a final bhurji with the leftover gravies and dal, over rice — nothing wasted, even at the feast",
      estCalories: 710,
      estProtein: 26,
    },
  ],
  shopping: [
    { item: "Whole milk (to curdle into paneer)", qty: "~1.5 gal", cost: 7.0, note: "the precious thread — the feast curdled at home" },
    { item: "Green peas (matar, frozen)", qty: "1 lb", cost: 2.0 },
    { item: "Spinach (for palak paneer)", qty: "2 bunches", cost: 3.0 },
    { item: "Cream (for shahi paneer)", qty: "1 small carton", cost: 2.5 },
    { item: "Cashews (for the shahi gravy)", qty: "small", cost: 2.5 },
    { item: "Toor dal (the base dal underneath)", qty: "1 lb", cost: 1.5 },
    { item: "Atta (whole wheat flour)", qty: "2 lb", cost: 1.5 },
    { item: "Basmati rice", qty: "2 lb", cost: 3.0 },
    { item: "Onions + tomatoes", qty: "~4 lb / ~3 lb", cost: 6.0, note: "the rich base for the gravies" },
    { item: "Ginger + garlic", qty: "1 hand / 2 heads", cost: 2.5, spansWeeks: true },
    { item: "Lemons (to curdle the milk)", qty: "4", cost: 1.5 },
    { item: "Green chiles + cilantro", qty: "a handful / 1 bunch", cost: 1.5 },
    { item: "Garam masala + kasuri methi (top up)", qty: "", cost: 2.5, spansWeeks: true },
    { item: "Ghee (top up — the feast uses more)", qty: "1/2 lb", cost: 3.0, spansWeeks: true },
    { item: "Oil + salt", qty: "", cost: 2.0, spansWeeks: true },
  ],
  firstShopTotal: 29,
  steadyStateWeekly: 19,
};

export const northIndianWeeks: WeekPlan[] = [
  niWeek1Dal,
  niWeek2RajmaChole,
  niWeek3Sabzi,
  niWeek4Saag,
  niWeek5Kadhi,
  niWeek6Khichdi,
  niWeek7Paneer,
];
