import type { WeekPlan } from "../types";

// Challenge — Oaxaca (La Tierra de los Siete Moles). Regional southern-Mexican
// cucina povera, DISTINCT from the general Mexican "cocina del maíz" challenge.
// The Oaxacan FOUNDATION is the constant in every week's engine: nixtamal masa
// (tortillas/tlayudas) + the singular Oaxacan chiles (pasilla oaxaqueño,
// chilhuacle, chile de agua) + black frijoles cooked with hoja de aguacate + a
// tomato-chile salsa/recado base + quesillo & manteca/asiento. It is never a
// week theme; each of the seven weeks is a distinct real dinner sitting on it.

export const oxWeek1Tlayudas: WeekPlan = {
  slug: "ox-week-1-tlayudas",
  number: 1,
  cuisine: "oaxacan",
  theme: "Tlayudas & Masa",
  title: "Week 1 — Tlayudas & Masa",
  description:
    "The week starts where Oaxaca starts: at the comal. A giant tlayuda smeared with asiento and refried black beans, blistered crisp, becomes the table's plate and its bread at once. Around it gather the smaller masa antojitos — memelas, tetelas, empanadas — that are the everyday dinner of the valley.",
  context: `In Oaxaca the masa is everything, but it is the tlayuda — a thirty-centimeter tortilla, dried half-crisp on the comal — that is the regional signature, sold from braziers on every plaza after dark. The cook spreads it with asiento (the smoky brown dregs of rendered pork lard), a layer of frijoles refritos darkened with hoja de aguacate, strings of quesillo, and a smear of salsa, then folds and toasts it until it cracks. The smaller masa is just as daily: memelas pinched with a raised rim and a film of bean and salsa, tetelas folded into triangles around black beans, empanadas filled with a quick mole amarillo. Nothing here needs meat to be dinner — the masa and the bean do the work, and the asiento does the gilding.`,
  dishes: ["Tlayuda", "Memelas", "Tetelas", "Empanadas de amarillo"],
  proteinNote:
    "Black frijoles spread on every masa base plus a complete protein with the corn; quesillo and a fried egg stack the rest. The floor is met without meat.",
  preciousThread: "Asiento — the smoky brown asientos of rendered pork lard the tlayuda is built on. A spoonful gilds the whole week.",
  bonus: false,
  engine: [
    "Nixtamal masa — a press of corn tortillas, memelas & big tlayudas, the daily base (the constant base)",
    "Oaxacan chiles — pasilla oaxaqueño, chilhuacle & chile de agua, toasted for salsas and a quick amarillo",
    "Black frijoles — a pot simmered with hoja de aguacate, then refried dark for spreading",
    "Salsa/recado base + quesillo & asiento — a chile-tomato salsa, string cheese, and the smoky lard",
  ],
  days: [
    { day: "Sun", isCookDay: true, dinner: "tlayuda with asiento, refried black beans, quesillo and salsa, folded and toasted on the comal", estCalories: 620, estProtein: 22 },
    { day: "Mon", dinner: "memelas with a film of refried beans, salsa de chile pasilla and crumbled quesillo", estCalories: 540, estProtein: 18 },
    { day: "Tue", dinner: "tetelas — masa triangles folded around black beans and hoja santa, toasted", estCalories: 520, estProtein: 17 },
    { day: "Wed", dinner: "empanadas de amarillo — masa turnovers filled with a quick mole amarillo", estCalories: 560, estProtein: 16 },
    { day: "Thu", dinner: "tlayuda sencilla with beans, chile de agua salsa and a fried egg on top", estCalories: 600, estProtein: 21 },
    { day: "Fri", dinner: "memelas con asiento and quesillo, with a tomato-chile salsa", estCalories: 540, estProtein: 18 },
    { day: "Sat", dinner: "zero-waste: chilaquiles oaxaqueños from torn leftover tortillas in the week's salsa, topped with quesillo", estCalories: 500, estProtein: 16 },
  ],
  shopping: [
    { item: "Masa harina / nixtamal corn", qty: "5 lb", cost: 4.0, note: "tortillas, memelas & tlayudas, the base" },
    { item: "Black beans", qty: "2 lb", cost: 2.5, spansWeeks: true },
    { item: "Oaxacan chiles (pasilla oaxaqueño, guajillo, chile de agua)", qty: "assorted", cost: 5.0, spansWeeks: true },
    { item: "Quesillo (Oaxaca string cheese)", qty: "~¾ lb", cost: 5.0, spansWeeks: true },
    { item: "Asiento / pork lard", qty: "1 small tub", cost: 3.5, spansWeeks: true },
    { item: "Tomatoes", qty: "~3 lb", cost: 3.5 },
    { item: "White onions", qty: "~3 lb", cost: 2.5 },
    { item: "Garlic", qty: "2 heads", cost: 1.5, spansWeeks: true },
    { item: "Hoja de aguacate (avocado leaf)", qty: "a small bunch", cost: 1.5, spansWeeks: true },
    { item: "Hoja santa", qty: "a few leaves", cost: 1.5 },
    { item: "Eggs", qty: "1 dozen", cost: 3.5 },
    { item: "Limes + cilantro", qty: "6 / a bunch", cost: 2.0 },
  ],
  firstShopTotal: 29,
  steadyStateWeekly: 17,
};

export const oxWeek2Moles: WeekPlan = {
  slug: "ox-week-2-moles",
  number: 2,
  cuisine: "oaxacan",
  theme: "Moles (Los Siete)",
  title: "Week 2 — Moles (Los Siete)",
  description:
    "Oaxaca is the land of seven moles, and this is the week you grind one. A mole negro built on chilhuacle and burnt chile seeds, a sunny mole amarillo, a brick-red coloradito — each is a sauce that turns a fistful of beans, an egg, or a little chicken into a feast over the masa base.",
  context: `Mole is not a dish so much as a discipline — a paste of two dozen toasted things ground to silk on the metate and let down with broth until it coats a spoon. Oaxaca claims siete moles, and the three at the heart of this week are the workhorses: mole negro, almost black from chilhuacle and deliberately burnt chile seeds, with a whisper of chocolate; mole amarillo, brightened with chile de agua, hoja santa and a masa thickener; coloradito, brick-red and gentler. The frugal genius is that the mole is the luxury — you grind it once and it stretches all week over plain things. A ladle of mole over an egg, over beans, over a single boiled potato, is a banquet; the meat, when there is any, is an afterthought floating in the sauce.`,
  dishes: ["Mole negro", "Mole amarillo", "Mole coloradito", "Mole over egg, bean and tlayuda"],
  proteinNote:
    "Black frijoles and egg under the mole carry the floor; a little chicken stretches across several nights as garnish, not center.",
  preciousThread: "Chilhuacle negro — the rare, costly Oaxacan chile that gives mole negro its color and depth. A few go a long way.",
  bonus: false,
  engine: [
    "Nixtamal masa — fresh tortillas and a tlayuda to scoop and mop the moles (the constant base)",
    "Oaxacan chiles — chilhuacle, pasilla oaxaqueño & chile de agua, toasted as the backbone of the moles",
    "Black frijoles — a pot with hoja de aguacate, the bean that sits beside every mole plate",
    "Salsa/recado base + quesillo & manteca — the chile-tomato base, string cheese, and lard to fry the mole paste",
  ],
  days: [
    { day: "Sun", isCookDay: true, dinner: "mole negro ground on the metate, ladled over a boiled egg and black beans with tortillas", estCalories: 640, estProtein: 24 },
    { day: "Mon", dinner: "mole amarillo over masa dumplings (chochoyotes) and chayote", estCalories: 560, estProtein: 17 },
    { day: "Tue", dinner: "enmoladas — tortillas dipped in coloradito, folded with quesillo and onion", estCalories: 580, estProtein: 19 },
    { day: "Wed", dinner: "mole negro over a little shredded chicken with rice and beans on the side", estCalories: 620, estProtein: 26 },
    { day: "Thu", dinner: "mole amarillo with green beans and chochoyotes, tortillas to mop", estCalories: 540, estProtein: 16 },
    { day: "Fri", dinner: "tlayuda smeared with coloradito, beans and quesillo, toasted crisp", estCalories: 600, estProtein: 20 },
    { day: "Sat", dinner: "zero-waste: the last of every mole stirred together over beans and rice, with leftover tortillas", estCalories: 520, estProtein: 18 },
  ],
  shopping: [
    { item: "Masa harina / nixtamal corn", qty: "3 lb", cost: 3.0, note: "tortillas, tlayuda & chochoyotes" },
    { item: "Black beans", qty: "1.5 lb", cost: 2.0, spansWeeks: true },
    { item: "Chilhuacle + pasilla oaxaqueño + guajillo", qty: "assorted for mole", cost: 7.0, spansWeeks: true },
    { item: "Tomatoes + tomatillos", qty: "~3 lb / 1 lb", cost: 4.0 },
    { item: "Mexican chocolate / cacao", qty: "1 tablet", cost: 2.0, spansWeeks: true },
    { item: "Sesame seeds, almonds, raisins, plantain", qty: "small amounts", cost: 4.0 },
    { item: "Chicken (legs/thighs)", qty: "~1.5 lb", cost: 4.0 },
    { item: "Quesillo", qty: "~½ lb", cost: 3.5, spansWeeks: true },
    { item: "Hoja santa + hoja de aguacate", qty: "a few leaves each", cost: 2.0, spansWeeks: true },
    { item: "White onions + garlic", qty: "~3 lb / 2 heads", cost: 3.0, spansWeeks: true },
    { item: "Rice", qty: "1 lb", cost: 1.5, spansWeeks: true },
    { item: "Spices (cinnamon, clove, cumin, oregano)", qty: "small", cost: 2.0, spansWeeks: true },
  ],
  firstShopTotal: 32,
  steadyStateWeekly: 19,
};

export const oxWeek3Frijoles: WeekPlan = {
  slug: "ox-week-3-frijoles",
  number: 3,
  cuisine: "oaxacan",
  theme: "Frijoles & Quesillo",
  title: "Week 3 — Frijoles & Quesillo",
  description:
    "A pot of black beans simmered with hoja de aguacate and a wedge of quesillo is the cheapest, most honest dinner in Oaxaca. This week leans into it — molotes, enfrijoladas, entomatadas — the small everyday plates where bean and string cheese do everything.",
  context: `The black bean of Oaxaca is cooked frijoles de olla — earthenware pot, an onion, a clove of garlic, and the unmistakable aniseed scent of a toasted avocado leaf dropped in near the end. That pot is the bank account of the week. Mash some thick and you have the filling for molotes, masa torpedoes fried golden. Thin the rest with a little broth and you have enfrijoladas — tortillas drowned in bean sauce, folded around quesillo. Swap the bean for a tomato-chile sauce and you have entomatadas. Quesillo, the cheese wound into a ball like a skein of yarn, is the small luxury that turns a bowl of beans into something you look forward to.`,
  dishes: ["Frijoles de olla", "Molotes", "Enfrijoladas", "Entomatadas"],
  proteinNote:
    "Black beans with masa make a complete protein every night; quesillo and the occasional egg stack the rest. No meat needed.",
  preciousThread: "Quesillo — a wedge of Oaxaca's string cheese, unwound over hot beans so it pulls into threads.",
  bonus: false,
  engine: [
    "Nixtamal masa — tortillas for the enfrijoladas and a dough for molotes (the constant base)",
    "Oaxacan chiles — pasilla oaxaqueño & chile de agua, toasted into the bean and tomato sauces",
    "Black frijoles — a big pot with hoja de aguacate, half whole, half mashed for filling",
    "Salsa/recado base + quesillo & manteca — the tomato-chile base, string cheese, and lard for frying",
  ],
  days: [
    { day: "Sun", isCookDay: true, dinner: "frijoles de olla with hoja de aguacate, quesillo and warm tortillas", estCalories: 560, estProtein: 22 },
    { day: "Mon", dinner: "enfrijoladas — tortillas dipped in black bean sauce, folded with quesillo and onion", estCalories: 540, estProtein: 19 },
    { day: "Tue", dinner: "molotes — masa torpedoes stuffed with refried beans, fried, with salsa", estCalories: 580, estProtein: 18 },
    { day: "Wed", dinner: "entomatadas — tortillas in a tomato-chile sauce with quesillo and a fried egg", estCalories: 560, estProtein: 20 },
    { day: "Thu", dinner: "frijoles refritos with quesillo melted on top, tortillas to scoop", estCalories: 520, estProtein: 20 },
    { day: "Fri", dinner: "molotes de plátano y frijol with salsa de chile pasilla", estCalories: 560, estProtein: 16 },
    { day: "Sat", dinner: "zero-waste: a thick frijol soup from the last beans with torn tortillas and the cheese ends", estCalories: 500, estProtein: 18 },
  ],
  shopping: [
    { item: "Masa harina / nixtamal corn", qty: "4 lb", cost: 3.5, note: "tortillas & molote dough, the base" },
    { item: "Black beans", qty: "3 lb", cost: 3.5, spansWeeks: true },
    { item: "Quesillo", qty: "~1 lb", cost: 6.0, spansWeeks: true },
    { item: "Tomatoes", qty: "~3 lb", cost: 3.5 },
    { item: "Oaxacan chiles (pasilla, chile de agua)", qty: "assorted", cost: 3.0, spansWeeks: true },
    { item: "White onions", qty: "~3 lb", cost: 2.5 },
    { item: "Garlic", qty: "2 heads", cost: 1.5, spansWeeks: true },
    { item: "Hoja de aguacate", qty: "a small bunch", cost: 1.5, spansWeeks: true },
    { item: "Eggs", qty: "1 dozen", cost: 3.5 },
    { item: "Ripe plantain", qty: "2", cost: 1.5 },
    { item: "Lard or oil", qty: "for frying", cost: 3.0, spansWeeks: true },
    { item: "Limes + cilantro", qty: "6 / a bunch", cost: 2.0 },
  ],
  firstShopTotal: 28,
  steadyStateWeekly: 16,
};

export const oxWeek4Caldos: WeekPlan = {
  slug: "ox-week-4-caldos",
  number: 4,
  cuisine: "oaxacan",
  theme: "Caldos & Guisos",
  title: "Week 4 — Caldos & Guisos",
  description:
    "When the valley turns cold and damp, Oaxaca reaches for the pot — mole de olla thick with chayote and corn, the dark chichilo, a bone-broth caldo de res, the ancient toasted-corn segueza. Brothy, stretching, made to feed a table from a little.",
  context: `These are the soups that are really meals: a long pot, a few bones or none, a great deal of vegetable, and the masa or chile doing the heavy lifting. Mole de olla is a brothy guajillo-and-tomato stew with corn on the cob, chayote, green beans and a sprig of epazote. Chichilo negro is the smoky, near-black member of the seven moles, served as a brothy stew over beef and chochoyotes. Caldo de res oaxaqueño stretches a few marrow bones across a whole pot of vegetables. And segueza is the deep-country dish — coarsely ground toasted corn simmered with chile and a little meat until it thickens like porridge, a recipe older than the conquest. The trick everywhere is the same: the broth and the toasted corn make a little protein taste like plenty.`,
  dishes: ["Mole de olla", "Chichilo negro", "Caldo de res oaxaqueño", "Segueza"],
  proteinNote:
    "A few beef bones and a little meat flavor a whole pot; masa chochoyotes, toasted corn and beans on the side carry the floor.",
  preciousThread: "A couple of marrow beef bones — cheap, but they turn a pot of water and vegetables into a feast.",
  bonus: false,
  engine: [
    "Nixtamal masa — tortillas and chochoyotes (masa dumplings) dropped into the caldos (the constant base)",
    "Oaxacan chiles — chilhuacle for the chichilo, pasilla oaxaqueño & guajillo for the broths",
    "Black frijoles — a pot with hoja de aguacate, served alongside the soups",
    "Salsa/recado base + quesillo & manteca — the chile-tomato recado that seasons every pot",
  ],
  days: [
    { day: "Sun", isCookDay: true, dinner: "mole de olla — brothy guajillo stew with corn, chayote, green beans and chochoyotes", estCalories: 540, estProtein: 20 },
    { day: "Mon", dinner: "chichilo negro — smoky near-black mole-stew over a little beef and chochoyotes", estCalories: 580, estProtein: 24 },
    { day: "Tue", dinner: "caldo de res oaxaqueño with marrow bones, chayote, cabbage and tortillas", estCalories: 560, estProtein: 23 },
    { day: "Wed", dinner: "segueza — toasted-corn and chile stew thickened to a porridge, with a little pork", estCalories: 560, estProtein: 21 },
    { day: "Thu", dinner: "mole de olla again with extra chochoyotes and beans, tortillas to mop", estCalories: 520, estProtein: 18 },
    { day: "Fri", dinner: "caldo de frijol — black bean broth with epazote, quesillo and tortillas", estCalories: 500, estProtein: 19 },
    { day: "Sat", dinner: "zero-waste: every pot combined into one rich caldo with the last vegetables and tortillas", estCalories: 520, estProtein: 20 },
  ],
  shopping: [
    { item: "Masa harina / nixtamal corn", qty: "3 lb", cost: 3.0, note: "tortillas & chochoyotes" },
    { item: "Black beans", qty: "1.5 lb", cost: 2.0, spansWeeks: true },
    { item: "Beef marrow bones + a little stewing beef", qty: "~2 lb", cost: 6.0 },
    { item: "Chilhuacle + guajillo + pasilla oaxaqueño", qty: "assorted", cost: 5.0, spansWeeks: true },
    { item: "Chayote + corn on the cob", qty: "3 / 4 ears", cost: 3.5 },
    { item: "Green beans + cabbage + carrots", qty: "a mix", cost: 3.5 },
    { item: "Tomatoes", qty: "~2 lb", cost: 2.5 },
    { item: "White onions + garlic", qty: "~2 lb / 2 heads", cost: 2.5, spansWeeks: true },
    { item: "Toasted corn for segueza", qty: "~1 lb", cost: 2.0 },
    { item: "Epazote + hoja de aguacate", qty: "bunches", cost: 2.0, spansWeeks: true },
    { item: "A little pork", qty: "~¾ lb", cost: 3.0 },
    { item: "Quesillo + limes", qty: "~¼ lb / 6", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 31,
  steadyStateWeekly: 18,
};

export const oxWeek5Salsas: WeekPlan = {
  slug: "ox-week-5-salsas",
  number: 5,
  cuisine: "oaxacan",
  theme: "Salsas & Chiles",
  title: "Week 5 — Salsas & Chiles",
  description:
    "This is the week the chile itself is the dinner. The smoky salsa de chile pasilla oaxaqueño, the pungent chintextle smeared on a tlayuda, the garlicky chileajo, and arroz a la oaxaqueña — proof that a fistful of toasted chiles can carry a table.",
  context: `Oaxacan chiles are unlike any others — the pasilla oaxaqueño is smoked over wood until it tastes of campfire and dried fruit; the chile de agua is the fresh green chile of the valley, roasted and peeled; chilhuacle is the prized one. This week they stop being a seasoning and become the plate. Salsa de chile pasilla oaxaqueño is so dense and smoky it is eaten almost like a spread. Chintextle is a thick paste of toasted pasilla, garlic, avocado leaf and dried shrimp, smeared a millimeter thick on a tlayuda and eaten as is — pure umami for pennies. Chileajo bathes vegetables in a garlicky guajillo sauce. The lesson of the week is the lesson of the whole cuisine: the chile does the work that money can't.`,
  dishes: ["Salsa de chile pasilla", "Chintextle on tlayudas", "Chileajo", "Arroz a la oaxaqueña"],
  proteinNote:
    "Beans under every salsa and a little dried shrimp in the chintextle carry the floor; eggs and quesillo stack the rest.",
  preciousThread: "Dried shrimp (camarón seco) — a small bag pounded into chintextle gives the whole week its savory backbone.",
  bonus: false,
  engine: [
    "Nixtamal masa — tortillas and tlayudas to carry every salsa and paste (the constant base)",
    "Oaxacan chiles — pasilla oaxaqueño, chile de agua & guajillo, toasted as the star of the week",
    "Black frijoles — a pot with hoja de aguacate, spread under each salsa",
    "Salsa/recado base + quesillo & manteca — the foundation chile-tomato salsa, string cheese, and lard",
  ],
  days: [
    { day: "Sun", isCookDay: true, dinner: "tlayuda con chintextle — thick toasted-pasilla paste smeared on the masa with beans and quesillo", estCalories: 560, estProtein: 19 },
    { day: "Mon", dinner: "huevos en salsa de chile pasilla oaxaqueño with tortillas and beans", estCalories: 540, estProtein: 21 },
    { day: "Tue", dinner: "chileajo de verduras — vegetables in garlicky guajillo sauce over rice", estCalories: 520, estProtein: 15 },
    { day: "Wed", dinner: "arroz a la oaxaqueña — rice with chile de agua, peas and quesillo, eggs on top", estCalories: 560, estProtein: 18 },
    { day: "Thu", dinner: "memelas con chintextle and crumbled quesillo", estCalories: 520, estProtein: 17 },
    { day: "Fri", dinner: "frijoles with salsa de chile pasilla and a fried egg, tortillas to scoop", estCalories: 540, estProtein: 20 },
    { day: "Sat", dinner: "zero-waste: arroz frito with the last vegetables, beans and every leftover salsa stirred through", estCalories: 520, estProtein: 17 },
  ],
  shopping: [
    { item: "Masa harina / nixtamal corn", qty: "4 lb", cost: 3.5, note: "tortillas & tlayudas, the base" },
    { item: "Black beans", qty: "1.5 lb", cost: 2.0, spansWeeks: true },
    { item: "Pasilla oaxaqueño + chile de agua + guajillo", qty: "a good handful each", cost: 6.0, spansWeeks: true },
    { item: "Dried shrimp (camarón seco)", qty: "1 small bag", cost: 3.0, spansWeeks: true },
    { item: "Rice", qty: "2 lb", cost: 2.5, spansWeeks: true },
    { item: "Tomatoes", qty: "~2 lb", cost: 2.5 },
    { item: "Mixed vegetables (carrot, green bean, chayote, peas)", qty: "a mix", cost: 4.0 },
    { item: "Garlic", qty: "3 heads", cost: 2.0, spansWeeks: true },
    { item: "White onions", qty: "~2 lb", cost: 2.0 },
    { item: "Eggs", qty: "1 dozen", cost: 3.5 },
    { item: "Quesillo", qty: "~½ lb", cost: 3.5, spansWeeks: true },
    { item: "Hoja de aguacate + limes", qty: "a bunch / 6", cost: 2.0, spansWeeks: true },
  ],
  firstShopTotal: 30,
  steadyStateWeekly: 17,
};

export const oxWeek6Tamales: WeekPlan = {
  slug: "ox-week-6-tamales",
  number: 6,
  cuisine: "oaxacan",
  theme: "Tamales Oaxaqueños",
  title: "Week 6 — Tamales Oaxaqueños",
  description:
    "The Oaxacan tamal is wrapped not in corn husk but in a banana leaf, which steams the masa flatter and perfumes it green. This week is the great steam: tamales de mole negro, tamales de chepil flecked with the wild herb, and higaditos, the fiesta egg-and-broth dish.",
  context: `On feast days Oaxaca steams tamales by the hundred, and the regional mark is the banana leaf — it makes a flatter, silkier tamal than the husk and lends a faint green scent. Tamales de mole negro hide a spoon of the week-two mole and a little chicken inside soft masa. Tamales de chepil fold the tiny wild legume-herb chepil straight into the dough, so the whole thing tastes of the field — a pure vegetable tamal that costs almost nothing. Higaditos is the festival dish that bridges into the next: a soup of beaten egg cooked into a saffron-yellow chile broth, ladled over masa, the kind of thing made for a baptism or a wedding from very little. Making tamales is a whole-day, whole-family labor, and the batch feeds for days — frugality and feast in one wrapping.`,
  dishes: ["Tamales de mole negro", "Tamales de chepil", "Higaditos", "Tamal de frijol"],
  proteinNote:
    "Masa with beans or egg in every tamal makes the floor; chepil adds plant protein, and a little chicken stretches across the mole tamales.",
  preciousThread: "Chepil — the tiny wild herb folded raw into the masa, foraged-cheap but unmistakably Oaxacan.",
  bonus: false,
  engine: [
    "Nixtamal masa — a big batch beaten with lard for the tamales and daily tortillas (the constant base)",
    "Oaxacan chiles — chilhuacle & pasilla oaxaqueño for the mole filling and the higaditos broth",
    "Black frijoles — a pot with hoja de aguacate, the filling for the bean tamales",
    "Salsa/recado base + quesillo & manteca — the chile-tomato base, string cheese, and the lard that lightens the masa",
  ],
  days: [
    { day: "Sun", isCookDay: true, dinner: "tamales de mole negro in banana leaf with a little chicken, steamed in a big batch", estCalories: 600, estProtein: 23 },
    { day: "Mon", dinner: "tamales de chepil — masa folded with the wild herb, with salsa de chile de agua", estCalories: 540, estProtein: 17 },
    { day: "Tue", dinner: "tamal de frijol con hoja santa, with beans and a tomato salsa", estCalories: 540, estProtein: 19 },
    { day: "Wed", dinner: "higaditos — beaten egg cooked into a yellow chile broth over masa", estCalories: 520, estProtein: 22 },
    { day: "Thu", dinner: "steamed leftover tamales pan-crisped, with refried beans and quesillo", estCalories: 560, estProtein: 20 },
    { day: "Fri", dinner: "tamales de chepil with frijoles de olla and salsa", estCalories: 540, estProtein: 18 },
    { day: "Sat", dinner: "zero-waste: unwrapped leftover tamales torn into a masa-and-egg cazuela in the last broth", estCalories: 520, estProtein: 19 },
  ],
  shopping: [
    { item: "Masa harina / nixtamal corn", qty: "5 lb", cost: 4.0, note: "a big tamal batch plus tortillas" },
    { item: "Black beans", qty: "1.5 lb", cost: 2.0, spansWeeks: true },
    { item: "Banana leaves", qty: "1 pack", cost: 3.0 },
    { item: "Chepil (or substitute foraged herb)", qty: "a bunch", cost: 2.5 },
    { item: "Chilhuacle + pasilla oaxaqueño + guajillo", qty: "assorted", cost: 5.0, spansWeeks: true },
    { item: "Chicken (legs/thighs)", qty: "~1.5 lb", cost: 4.0 },
    { item: "Eggs", qty: "1.5 dozen", cost: 5.0 },
    { item: "Lard", qty: "for the masa", cost: 3.0, spansWeeks: true },
    { item: "Tomatoes", qty: "~2 lb", cost: 2.5 },
    { item: "Hoja santa + hoja de aguacate", qty: "leaves / a bunch", cost: 2.0, spansWeeks: true },
    { item: "White onions + garlic", qty: "~2 lb / 2 heads", cost: 2.5, spansWeeks: true },
    { item: "Quesillo + limes", qty: "~¼ lb / 6", cost: 3.0, spansWeeks: true },
  ],
  firstShopTotal: 32,
  steadyStateWeekly: 18,
};

export const oxWeek7Fiesta: WeekPlan = {
  slug: "ox-week-7-fiesta",
  number: 7,
  cuisine: "oaxacan",
  theme: "Antojitos & Fiesta",
  title: "Week 7 — Antojitos & Fiesta",
  description:
    "The arc ends at the fiesta table. Istmeño garnachas crackling with picadillo, chiles de agua stuffed with quesillo, a little tasajo seared over coals, and — the crown of every Oaxacan celebration — a true mole negro feast laid over the week's whole foundation.",
  context: `An Oaxacan fiesta is a controlled extravagance: a few special things made to stretch over a whole crowd, with the masa-and-bean foundation underneath holding it all up. Garnachas istmeñas, from the Isthmus, are small thick tortillas crowned with picadillo, cabbage and a sharp salsa. Chiles de agua rellenos stuff the valley's own roasted green chile with quesillo. Tasajo — thin, salted, air-dried beef seared fast over charcoal — is the one true splurge, sliced thin so a little feeds many. And the feast that crowns it all is mole negro, ground days ahead, poured over turkey or chicken with rice, beans and a stack of tortillas — the dish a family saves and labors for, the proof that the most frugal larder in Mexico produces its grandest table. Chapulines, the toasted grasshoppers, get sprinkled over the tlayudas as the thrifty, crunchy protein they have always been.`,
  dishes: ["Garnachas istmeñas", "Chiles de agua rellenos", "Tasajo asado", "Mole negro feast"],
  proteinNote:
    "Tasajo and the mole-feast chicken are the splurge, stretched thin; beans, egg, quesillo and chapulines carry the floor all week.",
  preciousThread: "Tasajo — a little air-dried, salted beef seared over coals; sliced thin, a small piece flavors the whole fiesta.",
  bonus: false,
  engine: [
    "Nixtamal masa — tortillas, garnacha bases and a feast-day tlayuda (the constant base)",
    "Oaxacan chiles — chilhuacle & pasilla oaxaqueño for the mole, chile de agua roasted for stuffing",
    "Black frijoles — a pot with hoja de aguacate, refried under every antojito",
    "Salsa/recado base + quesillo & manteca — the chile-tomato salsa, string cheese, and the lard and asiento for the feast",
  ],
  days: [
    { day: "Sun", isCookDay: true, dinner: "mole negro feast over chicken with rice, beans and warm tortillas", estCalories: 660, estProtein: 27 },
    { day: "Mon", dinner: "garnachas istmeñas — small masa rounds with picadillo, cabbage and salsa", estCalories: 560, estProtein: 19 },
    { day: "Tue", dinner: "chiles de agua rellenos de quesillo with a tomato salsa and beans", estCalories: 540, estProtein: 18 },
    { day: "Wed", dinner: "tasajo asado over coals with frijoles, salsa de chile pasilla and tortillas", estCalories: 620, estProtein: 28 },
    { day: "Thu", dinner: "tlayuda con tasajo y chapulines — beans, quesillo and toasted grasshoppers", estCalories: 600, estProtein: 24 },
    { day: "Fri", dinner: "enmoladas from the leftover mole negro with quesillo and onion", estCalories: 560, estProtein: 20 },
    { day: "Sat", dinner: "zero-waste: a fiesta-leftovers tlayuda piled with the last mole, beans, tasajo ends and chapulines", estCalories: 580, estProtein: 23 },
  ],
  shopping: [
    { item: "Masa harina / nixtamal corn", qty: "4 lb", cost: 3.5, note: "tortillas, garnachas & tlayudas" },
    { item: "Black beans", qty: "1.5 lb", cost: 2.0, spansWeeks: true },
    { item: "Tasajo (thin salted beef)", qty: "~1 lb", cost: 6.0 },
    { item: "Chicken or turkey for the mole", qty: "~1.5 lb", cost: 4.0 },
    { item: "Chilhuacle + pasilla oaxaqueño + guajillo", qty: "assorted for mole", cost: 5.0, spansWeeks: true },
    { item: "Chiles de agua (fresh)", qty: "~8", cost: 3.0 },
    { item: "Chapulines (toasted grasshoppers)", qty: "1 small bag", cost: 4.0 },
    { item: "Quesillo", qty: "~¾ lb", cost: 5.0, spansWeeks: true },
    { item: "Tomatoes + cabbage", qty: "~2 lb / 1 head", cost: 4.0 },
    { item: "White onions + garlic", qty: "~2 lb / 2 heads", cost: 2.5, spansWeeks: true },
    { item: "Rice + asiento/lard", qty: "1 lb / 1 tub", cost: 3.5, spansWeeks: true },
    { item: "Limes + cilantro", qty: "6 / a bunch", cost: 2.0 },
  ],
  firstShopTotal: 32,
  steadyStateWeekly: 19,
};

export const oaxacanWeeks: WeekPlan[] = [
  oxWeek1Tlayudas,
  oxWeek2Moles,
  oxWeek3Frijoles,
  oxWeek4Caldos,
  oxWeek5Salsas,
  oxWeek6Tamales,
  oxWeek7Fiesta,
];
