import type { WeekPlan } from "../types";

export const week1Pasta: WeekPlan = {
  slug: "week-1-pasta",
  number: 1,
  cuisine: "italian",
  theme: "Pasta",
  title: "Week 1 — Pasta",
  description:
    "The opening week, and the hard protein puzzle: pasta itself gives you almost none, so you engineer the 100g floor in through eggs, legumes, anchovy, tuna, and ricotta. That tension is the whole game, and it shows up on the scoreboard — pasta week posts a higher cost-per-100g-protein than bean week will.",
  context:
    `The Southern heartbeat. For the poor of Naples and the Mezzogiorno, dried pasta was the great equalizer — shelf-stable, filling, and able to carry a "sauce" made from almost nothing: garlic and oil (aglio e olio), a crushed tomato, chickpeas and their broth (pasta e ceci), toasted breadcrumbs standing in for cheese (la mollica, "the poor man's parmesan"). The art is in the sugo and the salted water. This week sets the pattern for everything that follows: a cheap starch made glorious by technique, not money.`,
  dishes: [
    "Spaghetti con la mollica (anchovy, garlic, chili, toasted crumbs)",
    "Pasta e ceci and pasta e fagioli",
    'Pasta cacio e uova ("poor carbonara")',
    "Pasta al pomodoro e tonno",
    "Pasta e patate; pasta alla Norma",
    "Frittata di pasta (the zero-waste finale)",
  ],
  proteinNote:
    "Engineered in through legumes, eggs, anchovy, tuna, and ricotta — the hardest protein week.",
  bonus: false,
  preciousThread: "The anchovy tin. Use it like seasoning, not a topping.",
  engine: [
    "pot-of-chickpeas",
    "pot-of-cannellini",
    "tomato-sugo",
    "lemon-pangrattato",
  ],
  days: [
    {
      day: "Sun",
      isCookDay: true,
      dinner: "spaghetti-con-la-mollica",
      estCalories: 690,
      estProtein: 22,
    },
    {
      day: "Mon",
      dinner: "pasta-e-fagioli",
      estCalories: 710,
      estProtein: 26,
    },
    {
      day: "Tue",
      dinner: "pasta-al-pomodoro-e-tonno",
      estCalories: 700,
      estProtein: 28,
    },
    {
      day: "Wed",
      dinner: "pasta-e-patate",
      estCalories: 660,
      estProtein: 19,
    },
    {
      day: "Thu",
      dinner:
        "spaghetti-aglio-olio with anchovy, broccoli rabe, white beans",
      estCalories: 720,
      estProtein: 24,
    },
    {
      day: "Fri",
      dinner: "pasta-alla-norma",
      estCalories: 680,
      estProtein: 20,
    },
    {
      day: "Sat",
      dinner: "frittata-di-pasta",
      estCalories: 730,
      estProtein: 30,
    },
  ],
  shopping: [
    { item: "Dried pasta, mixed shapes", qty: "~3 lb", cost: 6.0 },
    { item: "Dried chickpeas", qty: "1 lb", cost: 2.5 },
    { item: "Dried cannellini/borlotti", qty: "1 lb", cost: 2.5 },
    { item: "Canned tomatoes", qty: "3 × 28 oz", cost: 7.5 },
    {
      item: "Eggs",
      qty: "2 dozen",
      cost: 9.0,
      note: "your protein backbone this week",
    },
    { item: "Canned tuna", qty: "2 tins", cost: 5.0 },
    { item: "Anchovies", qty: "1 tin", cost: 4.0, spansWeeks: true },
    { item: "Ricotta", qty: "1 tub", cost: 5.0 },
    {
      item: "Pecorino/Parmesan",
      qty: "~½ lb",
      cost: 7.0,
      spansWeeks: true,
    },
    {
      item: "Olive oil, Spanish",
      qty: "1 L",
      cost: 13.0,
      spansWeeks: true,
    },
    { item: "Day-old bread", qty: "~1 loaf", cost: 4.0 },
    { item: "Broccoli rabe", qty: "1 bunch", cost: 3.5 },
    { item: "Eggplant", qty: "1", cost: 2.0 },
    { item: "Onions", qty: "~3 lb", cost: 3.0 },
    { item: "Garlic", qty: "2 heads", cost: 2.0, spansWeeks: true },
    { item: "Carrots + celery (soffritto)", qty: "", cost: 3.5 },
    { item: "Potatoes", qty: "~2 lb", cost: 2.5 },
    { item: "Lemons", qty: "3", cost: 1.5 },
    { item: "Parsley, rosemary", qty: "", cost: 3.0 },
  ],
  firstShopTotal: 32,
  steadyStateWeekly: 18,
};
